// =====================================================================================
// ResourcesCsvExporter.cs — SO → CSV (round-trip для ResourcesCsvImporter)
// =====================================================================================
// Документация:
//   • docs/Markets/Resources_import_export/02_DESIGN.md §4
//   • docs/Markets/Resources_import_export/03_TICKETS.md T-IE05
//
// Назначение: собирает CSV из 4 MVP-блоков (inventory, tradeItems, marketItems,
// exchangeRates) и пишет в файл. Используется для:
//   1. Round-trip тестов (Export → Re-import → no changes)
//   2. Content writer'ам: «что есть в проекте?» → открыть CSV в Excel
//
// recipes (Phase 2) — НЕ пишется (out of scope MVP). Управляются вручную.
//
// Прецедент: QuestCsvExporter (Assets/_Project/Quests/Editor/QuestCsvExporter.cs).
//
// T-IE05 (2026-06-12): MVP. ~200 LOC.
// =====================================================================================

#if UNITY_EDITOR
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;
using ProjectC.Trade;
using ProjectC.Trade.Config;

namespace ProjectC.Items.Editor
{
    public static class ResourcesCsvExporter
    {
        /// <summary>
        /// Экспортирует все 4 MVP-блока в CSV-файл. Возвращает число записанных строк данных.
        /// </summary>
        public static int Export(string csvPath)
        {
            if (string.IsNullOrEmpty(csvPath)) return 0;

            int rowsWritten = 0;
            var sb = new StringBuilder();
            var ci = CultureInfo.InvariantCulture;

            // Header comments
            sb.AppendLine("# Project C: The Clouds — Resources Database");
            sb.AppendLine("# Generated by Tools → ProjectC → Resources → CSV Import/Export");
            sb.AppendLine("# This file is the source of truth. .asset files are GENERATED from it.");
            sb.AppendLine();

            // -------- Block 1: inventory (ItemData) --------
            sb.AppendLine("# block=inventory");
            sb.AppendLine(string.Join(",", ResourcesCsvSchema.BlockInventory.Columns.Select(c => c.name)));
            var allItems = Resources.FindObjectsOfTypeAll<ItemData>();
            foreach (var item in allItems.OrderBy(i => i.itemName, System.StringComparer.OrdinalIgnoreCase))
            {
                if (item == null) continue;
                sb.AppendLine(string.Join(",", new[]
                {
                    EscapeCsv(item.itemName),
                    item.itemType.ToString(),
                    EscapeCsv(item.description ?? ""),
                    item.maxStack.ToString(ci),
                    item.weightKg.ToString("0.0##", ci),
                }));
                rowsWritten++;
            }
            sb.AppendLine();

            // -------- Block 2: tradeItems (TradeItemDefinition) --------
            sb.AppendLine("# block=tradeItems");
            sb.AppendLine(string.Join(",", ResourcesCsvSchema.BlockTradeItems.Columns.Select(c => c.name)));
            // 1. TradeItemDatabase.allItems (fast).
            var tdb = AssetDatabase.LoadAssetAtPath<TradeDatabase>(ResourcesCsvImporter.TRADE_ITEM_DATABASE_PATH);
            var seen = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            if (tdb != null)
            {
                foreach (var t in tdb.allItems.OrderBy(t => t.itemId, System.StringComparer.OrdinalIgnoreCase))
                {
                    if (t == null) continue;
                    WriteTradeItemRow(sb, t, ci);
                    seen.Add(t.itemId);
                    rowsWritten++;
                }
            }
            // 2. Scan for orphans (assets not in db).
            var guids = AssetDatabase.FindAssets("t:TradeItemDefinition", new[] { ResourcesCsvImporter.TRADE_ITEMS_FOLDER });
            foreach (var g in guids)
            {
                var p = AssetDatabase.GUIDToAssetPath(g);
                var t = AssetDatabase.LoadAssetAtPath<TradeItemDefinition>(p);
                if (t != null && !string.IsNullOrEmpty(t.itemId) && !seen.Contains(t.itemId))
                {
                    WriteTradeItemRow(sb, t, ci);
                    seen.Add(t.itemId);
                    rowsWritten++;
                }
            }
            sb.AppendLine();

            // -------- Block 3: marketItems (MarketConfig.items[]) --------
            sb.AppendLine("# block=marketItems");
            sb.AppendLine(string.Join(",", ResourcesCsvSchema.BlockMarketItems.Columns.Select(c => c.name)));
            var mcGuids = AssetDatabase.FindAssets("t:MarketConfig");
            foreach (var g in mcGuids)
            {
                var p = AssetDatabase.GUIDToAssetPath(g);
                var mc = AssetDatabase.LoadAssetAtPath<MarketConfig>(p);
                if (mc == null || mc.items == null) continue;
                foreach (var mic in mc.items)
                {
                    if (mic == null) continue;
                    sb.AppendLine(string.Join(",", new[]
                    {
                        EscapeCsv(mic.itemId),
                        EscapeCsv(mc.locationId),
                        mic.basePrice.ToString(ci),
                        mic.initialStock.ToString(ci),
                        mic.regenPerTick.ToString("0.0####", ci),
                        mic.factionRestriction.ToString(),
                        mic.allowBuy ? "y" : "n",
                        mic.allowSell ? "y" : "n",
                    }));
                    rowsWritten++;
                }
            }
            sb.AppendLine();

            // -------- Block 4: exchangeRates (ExchangeRateConfig.rates[]) --------
            sb.AppendLine("# block=exchangeRates");
            sb.AppendLine(string.Join(",", ResourcesCsvSchema.BlockExchangeRates.Columns.Select(c => c.name)));
            var erc = AssetDatabase.LoadAssetAtPath<ExchangeRateConfig>(ResourcesCsvImporter.EXCHANGE_RATE_CONFIG_PATH);
            if (erc != null && erc.rates != null)
            {
                foreach (var r in erc.rates)
                {
                    sb.AppendLine(string.Join(",", new[]
                    {
                        EscapeCsv(r.warehouseItemId),
                        EscapeCsv(r.inventoryItemName),
                        r.warehouseQty.ToString(ci),
                        r.inventoryQty.ToString(ci),
                        EscapeCsv(r.displayName ?? ""),
                    }));
                    rowsWritten++;
                }
            }
            sb.AppendLine();

            // -------- Block 5: recipes — Phase 2 (skipped) --------

            // Write file (UTF-8 with BOM for Excel).
            var dir = Path.GetDirectoryName(csvPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);
            File.WriteAllText(csvPath, sb.ToString(), new UTF8Encoding(true));
            AssetDatabase.Refresh();

            return rowsWritten;
        }

        private static void WriteTradeItemRow(StringBuilder sb, TradeItemDefinition t, CultureInfo ci)
        {
            sb.AppendLine(string.Join(",", new[]
            {
                EscapeCsv(t.itemId),
                EscapeCsv(t.displayName ?? ""),
                t.basePrice.ToString(ci),
                t.weight.ToString(ci),
                t.volume.ToString("0.0##", ci),
                t.slots.ToString(ci),
                t.isDangerous ? "y" : "n",
                t.isFragile ? "y" : "n",
                t.isContraband ? "y" : "n",
                t.requiredFaction.ToString(),
            }));
        }

        // ============================================================
        // CSV escaping (RFC 4180: quote field if contains comma/quote/newline, escape " as "")
        // ============================================================

        private static string EscapeCsv(string value)
        {
            if (string.IsNullOrEmpty(value)) return "";
            if (value.Contains(',') || value.Contains('"') || value.Contains('\n') || value.Contains('\r'))
                return "\"" + value.Replace("\"", "\"\"") + "\"";
            return value;
        }

        // ============================================================
        // Editor menu: Tools → ProjectC → Resources → Export to CSV
        // ============================================================

        [MenuItem("Tools/ProjectC/Resources/Export to CSV", priority = 200)]
        public static void ExportMenuItem()
        {
            var path = EditorUtility.SaveFilePanel(
                "Export Resources CSV",
                Application.dataPath,
                "Resources_Import.csv",
                "csv");
            if (string.IsNullOrEmpty(path)) return;

            int rows = Export(path);
            Debug.Log($"[ResourcesCsvExporter] Exported {rows} rows to {path}");
            EditorUtility.DisplayDialog("Export complete",
                $"Exported {rows} rows to:\n{path}", "OK");
        }
    }
}
#endif
