// CloudGenerator.cs v7.0
// Generated by Cloud Generator Visualizer
// DO NOT EDIT - Regenerate from visualizer

using System;
using System.Collections.Generic;
using UnityEngine;

namespace ProjectC.CloudGenerator
{
    public struct DeterministicRandom
    {
        private uint _state;

        public DeterministicRandom(int seed)
        {
            _state = (uint)(seed != 0 ? seed : 1);
            for (int i = 0; i < 10; i++)
            {
                uint x = _state;
                x ^= x << 13;
                x ^= x >> 17;
                x ^= x << 5;
                _state = x;
            }
        }

        public uint Next()
        {
            uint x = _state;
            x ^= x << 13;
            x ^= x >> 17;
            x ^= x << 5;
            _state = x;
            return x;
        }

        public double NextDouble() => Next() / (double)uint.MaxValue;
    }

    public static class CloudGenerator
    {
        public static List<CloudSphere> Generate(List<CloudLayerConfig> layers)
        {
            var allSpheres = new List<CloudSphere>();
            double cumulativeY = 0;

            for (int i = 0; i < layers.Count; i++)
            {
                CloudLayerConfig layer = layers[i];
                if (!layer.Enabled) continue;

                var rng = new DeterministicRandom(layer.Seed);
                List<CloudSphere> rawSpheres;

                switch (layer.Archetype)
                {
                    case CloudArchetype.Sphere:
                        rawSpheres = GenerateSphereLayer(layer, ref rng);
                        break;
                    case CloudArchetype.Column:
                        rawSpheres = GenerateColumnLayer(layer, ref rng);
                        break;
                    case CloudArchetype.Platform:
                        rawSpheres = GeneratePlatformLayer(layer, ref rng);
                        break;
                    case CloudArchetype.Tree:
                        rawSpheres = GenerateTreeLayer(layer, ref rng);
                        break;
                    default:
                        rawSpheres = GenerateSphereLayer(layer, ref rng);
                        break;
                }

                double minY = double.MaxValue;
                double maxY = double.MinValue;
                for (int si = 0; si < rawSpheres.Count; si++)
                {
                    double bottom = rawSpheres[si].Y - rawSpheres[si].Radius;
                    double top = rawSpheres[si].Y + rawSpheres[si].Radius;
                    if (bottom < minY) minY = bottom;
                    if (top > maxY) maxY = top;
                }

                const double gap = 2.0;
                double yOffset = Math.Abs(layer.YOffset) > 0.001
                    ? layer.YOffset
                    : cumulativeY - minY + gap;

                bool hasCondensation = layer.CondensationLevel != -999;

                for (int si = 0; si < rawSpheres.Count; si++)
                {
                    CloudSphere s = rawSpheres[si];
                    s.Y += (float)yOffset;
                    s.LayerIndex = i;
                    s.CutByCondensation = hasCondensation && (s.Y - s.Radius < layer.CondensationLevel);
                }

                cumulativeY = yOffset + maxY + gap;
                allSpheres.AddRange(rawSpheres);
            }

            allSpheres.RemoveAll(s => s.CutByCondensation);
            return allSpheres;
        }

        private struct SphereGenFrame
        {
            public double X, Y, Z;
            public double Radius;
            public int Depth;
            public double Density;
            public int NextPointIdx;
            public int BumpCount;
            public (double x, double y, double z)[] SurfacePoints;
        }

        private static List<CloudSphere> GenerateSphereLayer(CloudLayerConfig layer, ref DeterministicRandom rng)
        {
            var spheres = new List<CloudSphere>();
            int globalUniqueId = 0;

            float sphereCountScale = layer.SphereCountScale > 0 ? layer.SphereCountScale : 1.0f;
            int maxSphereCount = (int)(layer.MaxSphereCount * sphereCountScale);
            double cloudSize = layer.CloudSize;
            double density = layer.Density;
            int seed = layer.Seed;
            int cascadeDepth = layer.CascadeDepth;
            int bumpsPerLevel = layer.BumpsPerLevel;
            double childRatio = layer.ChildRatio;
            double sizeVariation = layer.SizeVariation;
            double jitter = layer.Jitter;
            double clustering = layer.Clustering;
            int parentCount = layer.ParentCount;
            double ellipsoidY = layer.EllipsoidY;
            double ellipsoidXZ = layer.EllipsoidXZ;
            int noiseSalt = layer.NoiseSalt;

            double minRadius = layer.SizeRange.Min;
            double sizeMax = layer.SizeRange.Max;
            double baseRadius = cloudSize * 0.5;

            double rx = baseRadius * (ellipsoidXZ / 100.0);
            double ry = baseRadius * (ellipsoidY / 100.0);
            double rz = baseRadius * (ellipsoidXZ / 100.0);
            double posVariation = layer.PositionVariation;

            List<Vector3> parentMeshPoints = null;
            if (!string.IsNullOrEmpty(layer.ParentMeshPath))
            {
                parentMeshPoints = SampleMeshPoints(layer, ref rng);
            }

            var stack = new Stack<SphereGenFrame>();

            if (parentMeshPoints != null)
            {
                int meshPointCount = parentMeshPoints.Count;
                int parentLimit = (int)Math.Min(maxSphereCount, meshPointCount);
                for (int i = 0; i < parentLimit; i++)
                {
                    var mp = parentMeshPoints[i];
                    spheres.Add(new CloudSphere
                    {
                        X = mp.x, Y = mp.y, Z = mp.z,
                        Radius = (float)(baseRadius * 0.3), Depth = 0, Density = 1.0f,
                        Archetype = CloudArchetype.Sphere
                    });

                    stack.Push(new SphereGenFrame
                    {
                        X = mp.x, Y = mp.y, Z = mp.z, Radius = baseRadius * 0.3,
                        Depth = 0, Density = 1.0,
                        NextPointIdx = -1, BumpCount = 0, SurfacePoints = null
                    });
                }
            }
            else
            {
                for (int p = 0; p < parentCount; p++)
                {
                    double offsetAngle = (p / (double)parentCount) * Math.PI * 2;
                    double spread = parentCount > 1 ? (p % 3) * 0.15 : 0;
                    double px = Math.Cos(offsetAngle) * rx * spread;
                    double py = (p % 2 == 0 ? 1 : -1) * ry * 0.1 * spread;
                    double pz = Math.Sin(offsetAngle) * rz * spread;

                    spheres.Add(new CloudSphere
                    {
                        X = (float)px, Y = (float)py, Z = (float)pz,
                        Radius = (float)baseRadius, Depth = 0, Density = 1.0f,
                        Archetype = CloudArchetype.Sphere
                    });

                    stack.Push(new SphereGenFrame
                    {
                        X = px, Y = py, Z = pz, Radius = baseRadius,
                        Depth = 0, Density = 1.0,
                        NextPointIdx = -1, BumpCount = 0, SurfacePoints = null
                    });
                }
            }

            while (stack.Count > 0 && spheres.Count < maxSphereCount)
            {
                SphereGenFrame frame = stack.Pop();

                if (frame.NextPointIdx == -1)
                {
                    if (frame.Depth >= cascadeDepth) continue;
                    if (frame.Radius < minRadius * 1.5) continue;

                    double noiseForBumpCount = (CloudMath.Perlin3D(
                        frame.X * 0.5, frame.Y * 0.5, frame.Z * 0.5,
                        seed + frame.Depth * 7) + 1.0) * 0.5;
                    int actualBumps = (int)Math.Floor(bumpsPerLevel * (0.4 + noiseForBumpCount * 0.8));

                    var surfacePoints = CloudMath.FibonacciSphere(
                        frame.X, frame.Y, frame.Z,
                        frame.Radius, frame.Radius, frame.Radius, actualBumps);

                    frame.NextPointIdx = 0;
                    frame.BumpCount = actualBumps;
                    frame.SurfacePoints = surfacePoints;
                }

                if (frame.NextPointIdx >= frame.BumpCount) continue;

                int idx = frame.NextPointIdx;
                (double x, double y, double z) pt = frame.SurfacePoints[idx];

                double nx = (pt.x - frame.X) / frame.Radius;
                double ny = (pt.y - frame.Y) / frame.Radius;
                double nz = (pt.z - frame.Z) / frame.Radius;

                double jitterStrength = jitter / 100.0;
                double jitX = CloudMath.Perlin3D(pt.x * 15, pt.y * 15, pt.z * 15, seed) * jitterStrength;
                double jitY = CloudMath.Perlin3D(pt.x * 15, pt.y * 15, pt.z * 15, seed + 1) * jitterStrength;
                double jitZ = CloudMath.Perlin3D(pt.x * 15, pt.y * 15, pt.z * 15, seed + 2) * jitterStrength;
                double jptX = pt.x + jitX * frame.Radius;
                double jptY = pt.y + jitY * frame.Radius;
                double jptZ = pt.z + jitZ * frame.Radius;

                double noiseScale = 3.0 / frame.Radius;

                double worleyVal = CloudMath.InvertedWorley(
                    jptX * noiseScale * 2, jptY * noiseScale * 2, jptZ * noiseScale * 2,
                    1.0, noiseSalt);

                double clusterStrength = clustering / 100.0;

                double fbmVal = (CloudMath.Fbm(
                    jptX * noiseScale, jptY * noiseScale, jptZ * noiseScale,
                    4, 0.5, 2.0, seed + frame.Depth * 10) + 1.0) * 0.5;

                double bumpIntensity = fbmVal * (1.0 - clusterStrength * 0.5)
                                       + worleyVal * clusterStrength * 0.5;

                double threshold = 1.0 - density;

                if (bumpIntensity < threshold)
                {
                    if (!(worleyVal > 0.75 && rng.NextDouble() < 0.15))
                    {
                        frame.NextPointIdx = idx + 1;
                        if (frame.NextPointIdx < frame.BumpCount) stack.Push(frame);
                        continue;
                    }
                }

                double phiNoise = (CloudMath.Perlin3D(
                    jptX * noiseScale, jptY * noiseScale, jptZ * noiseScale,
                    seed + 100) + 1.0) * 0.5;
                double effectiveRatio = (CloudMath.PHI + (phiNoise - 0.5) * 0.6)
                                        * (childRatio / 100.0) * 0.4;

                int childUniqueId = globalUniqueId++;

                double sizeNoiseBase = Math.Pow(
                    (CloudMath.Perlin3D(
                        jptX * noiseScale * 2, jptY * noiseScale * 2, jptZ * noiseScale * 2,
                        seed + childUniqueId) + 1.0) * 0.5, 1.5);
                double sizeNoiseMult = Math.Pow(
                    (CloudMath.Perlin3D(
                        jptX * noiseScale * 2 + 100, jptY * noiseScale * 2 + 100, jptZ * noiseScale * 2 + 100,
                        seed + childUniqueId + 500) + 1.0) * 0.5, 1.5);

                double sizeBase = minRadius + sizeNoiseBase * (sizeMax - minRadius);
                double sizeMult = (0.05 + sizeNoiseMult * sizeVariation * 2.0 + effectiveRatio) * 0.3;
                double childRadius = sizeBase * sizeMult;

                if (childRadius < minRadius * 0.1)
                {
                    frame.NextPointIdx = idx + 1;
                    if (frame.NextPointIdx < frame.BumpCount) stack.Push(frame);
                    continue;
                }

                var perturbed = CloudMath.PerturbDir(
                    nx, ny, nz, jptX, jptY, jptZ, 0.25, seed + frame.Depth);

                double posOffX = (rng.NextDouble() - 0.5) * 12.0 * frame.Radius * posVariation;
                double posOffY = (rng.NextDouble() - 0.5) * 12.0 * frame.Radius * posVariation;
                double posOffZ = (rng.NextDouble() - 0.5) * 12.0 * frame.Radius * posVariation;

                double childX = jptX + perturbed.x * frame.Radius * 0.02 + posOffX;
                double childY = jptY + perturbed.y * frame.Radius * 0.02 + posOffY;
                double childZ = jptZ + perturbed.z * frame.Radius * 0.02 + posOffZ;

                spheres.Add(new CloudSphere
                {
                    X = (float)childX, Y = (float)childY, Z = (float)childZ,
                    Radius = (float)childRadius,
                    Depth = frame.Depth + 1, Density = (float)bumpIntensity,
                    Archetype = CloudArchetype.Sphere
                });

                if (spheres.Count >= maxSphereCount) break;

                frame.NextPointIdx = idx + 1;
                if (frame.NextPointIdx < frame.BumpCount) stack.Push(frame);

                double continueChance = Math.Max(0.15, 0.8 - frame.Depth * 0.2);
                bool shouldRecurse = (rng.NextDouble() < continueChance || frame.Depth < 2)
                                     && spheres.Count < maxSphereCount;

                if (shouldRecurse)
                {
                    stack.Push(new SphereGenFrame
                    {
                        X = childX, Y = childY, Z = childZ,
                        Radius = childRadius, Depth = frame.Depth + 1, Density = bumpIntensity,
                        NextPointIdx = -1, BumpCount = 0, SurfacePoints = null
                    });
                }
            }

            return spheres;
        }

#if UNITY_EDITOR
        private static List<Vector3> SampleMeshPoints(CloudLayerConfig layer, ref DeterministicRandom rng)
        {
            var meshAsset = UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Mesh>(layer.ParentMeshPath);
            if (meshAsset == null) return null;

            var points = new List<Vector3>();
            var vertices = meshAsset.vertices;
            var triangles = meshAsset.triangles;

            int triCount = triangles.Length / 3;
            var triAreas = new float[triCount];
            var cumAreas = new float[triCount];

            float totalArea = 0f;
            for (int i = 0; i < triCount; i++)
            {
                int i0 = triangles[i * 3];
                int i1 = triangles[i * 3 + 1];
                int i2 = triangles[i * 3 + 2];

                Vector3 v0 = vertices[i0];
                Vector3 v1 = vertices[i1];
                Vector3 v2 = vertices[i2];

                Vector3 e1 = v1 - v0;
                Vector3 e2 = v2 - v0;
                float area = Vector3.Cross(e1, e2).magnitude * 0.5f;

                if (area > 0.0001f)
                {
                    triAreas[i] = area;
                    totalArea += area;
                    cumAreas[i] = totalArea;
                }
                else
                {
                    triAreas[i] = 0f;
                    cumAreas[i] = totalArea;
                }
            }

            if (totalArea <= 0f) return null;

            int targetCount = layer.MaxSphereCount > 0 ? layer.MaxSphereCount : 2000;
            int sampleCount = Math.Min(targetCount, 2000);
            for (int p = 0; p < sampleCount; p++)
            {
                double r = rng.NextDouble() * totalArea;

                int triIdx = Array.BinarySearch(cumAreas, (float)r);
                if (triIdx < 0) triIdx = ~triIdx;
                if (triIdx >= triCount) triIdx = triCount - 1;

                int j0 = triangles[triIdx * 3];
                int j1 = triangles[triIdx * 3 + 1];
                int j2 = triangles[triIdx * 3 + 2];

                Vector3 w0 = vertices[j0];
                Vector3 w1 = vertices[j1];
                Vector3 w2 = vertices[j2];

                double u = rng.NextDouble();
                double v = rng.NextDouble();
                double sqrtU = Math.Sqrt(u);

                double a = 1.0 - sqrtU;
                double b = sqrtU * (1.0 - v);
                double c = sqrtU * v;

                points.Add(new Vector3(
                    (float)(a * w0.x + b * w1.x + c * w2.x),
                    (float)(a * w0.y + b * w1.y + c * w2.y),
                    (float)(a * w0.z + b * w1.z + c * w2.z)
                ));
            }

            if (points.Count == 0) return null;

            float sx = layer.ParentMeshScaleX;
            float sy = layer.ParentMeshScaleY;
            float sz = layer.ParentMeshScaleZ;
            float rx = layer.ParentMeshRotX * (float)(Math.PI / 180.0);
            float ry = layer.ParentMeshRotY * (float)(Math.PI / 180.0);
            float rz = layer.ParentMeshRotZ * (float)(Math.PI / 180.0);
            float ox = layer.ParentMeshOffsetX;
            float oy = layer.ParentMeshOffsetY;
            float oz = layer.ParentMeshOffsetZ;

            float cosZ = (float)Math.Cos(rz), sinZ = (float)Math.Sin(rz);
            float cosY = (float)Math.Cos(ry), sinY = (float)Math.Sin(ry);
            float cosX = (float)Math.Cos(rx), sinX = (float)Math.Sin(rx);

            var result = new List<Vector3>(points.Count);
            foreach (var pt in points)
            {
                float tsx = pt.x * sx;
                float tsy = pt.y * sy;
                float tsz = pt.z * sz;

                float rx2 = tsx * cosZ - tsy * sinZ;
                float ry2 = tsx * sinZ + tsy * cosZ;
                float rz2 = tsz;

                float rx3 = rx2 * cosY + rz2 * sinY;
                float ry3 = ry2;
                float rz3 = -rx2 * sinY + rz2 * cosY;

                float rx4 = rx3;
                float ry4 = ry3 * cosX - rz3 * sinX;
                float rz4 = ry3 * sinX + rz3 * cosX;

                result.Add(new Vector3(rx4 + ox, ry4 + oy, rz4 + oz));
            }

            return result;
        }
#endif

        private static List<CloudSphere> GenerateColumnLayer(CloudLayerConfig layer, ref DeterministicRandom rng)
        {
            var spheres = new List<CloudSphere>();

            int seed = layer.Seed;
            double jitter = layer.Jitter;
            double posVariation = layer.PositionVariation;
            int sizeMin = layer.SizeRange.Min;
            int sizeMax = layer.SizeRange.Max;

            double height = layer.ColumnParams.Height;
            double baseRadius = layer.ColumnParams.BaseRadius;
            double topRadius = layer.ColumnParams.TopRadius;
            int floors = layer.ColumnParams.Floors;
            int ringsPerFloor = layer.ColumnParams.RingsPerFloor;
            double wobble = layer.ColumnParams.Wobble / 100.0;

            double floorSpacing = height / floors;

            for (int floor = 0; floor < floors; floor++)
            {
                double t = floor / (double)(floors - 1 <= 0 ? 1 : floors - 1);
                double floorRadius = baseRadius + (topRadius - baseRadius) * t;

                double y = floor * floorSpacing;

                double wobbleX = CloudMath.Perlin3D(floor * 0.0, 0, 0, seed)
                                 * wobble * floorRadius
                                 + jitter * baseRadius * 2.0
                                    * CloudMath.Perlin3D(floor, 0, 0, seed + 1);
                double wobbleZ = CloudMath.Perlin3D(floor * 0.7, 0, 0, seed + 100)
                                 * wobble * floorRadius
                                 + jitter * baseRadius * 2.0
                                    * CloudMath.Perlin3D(floor, 0, 0, seed + 2);

                for (int r = 0; r < ringsPerFloor; r++)
                {
                    double angle = (r / (double)ringsPerFloor) * Math.PI * 2
                                   + CloudMath.Perlin3D(floor * 0.3, r * 0.5, seed, seed)
                                     * 0.5 * (1.0 + jitter * 2.0);
                     double distNoise = CloudMath.Perlin3D(floor * 0.5, r * 0.7, seed + 50, seed);
                    double distFromCenter = floorRadius
                                            * (0.3 + (distNoise + 1.0) * 0.5 * 0.7 + 0.5)
                                            * 0.5;
                     double jitR = CloudMath.Perlin3D(floor, r, seed, seed) * jitter * 0.5;

                    double rNoiseBase = Math.Pow(
                         (CloudMath.Perlin3D(floor + r * 0.1, r + floor * 0.1, seed + 200, seed)
                          + 1.0) * 0.5, 1.8);
                    double rNoiseMult = Math.Pow(
                         (CloudMath.Perlin3D(floor + r * 0.1 + 50, r + floor * 0.1 + 50, seed + 250, seed)
                         + 1.0) * 0.5, 1.5);
                    double sizeBase = sizeMin + rNoiseBase * (sizeMax - sizeMin);
                    double sphereRadius = baseRadius * sizeBase * 0.12 * (0.1 + rNoiseMult * 0.9);

                    double colOx = (rng.NextDouble() - 0.5) * 12.0 * sphereRadius * posVariation;
                    double colOy = (rng.NextDouble() - 0.5) * 12.0 * sphereRadius * posVariation;
                    double colOz = (rng.NextDouble() - 0.5) * 12.0 * sphereRadius * posVariation;

                    spheres.Add(new CloudSphere
                    {
                        X = (float)(Math.Cos(angle) * distFromCenter + wobbleX + colOx),
                        Y = (float)(y + jitR * 0.3 + colOy),
                        Z = (float)(Math.Sin(angle) * distFromCenter + wobbleZ + colOz),
                        Radius = (float)Math.Max(sphereRadius, 0.5),
                        Depth = 0, Density = (float)(0.6 + (1.0 - t) * 0.3),
                        Archetype = CloudArchetype.Column
                    });
                }

                if (floor % 2 == 0)
                {
                    spheres.Add(new CloudSphere
                    {
                        X = (float)wobbleX, Y = (float)y, Z = (float)wobbleZ,
                        Radius = (float)(floorRadius * 0.3),
                        Depth = 0, Density = 0.8f,
                        Archetype = CloudArchetype.Column
                    });
                }
            }

            return spheres;
        }

        private static List<CloudSphere> GeneratePlatformLayer(CloudLayerConfig layer, ref DeterministicRandom rng)
        {
            var spheres = new List<CloudSphere>();

            int seed = layer.Seed;
            double jitter = layer.Jitter;
            double clustering = layer.Clustering;
            double posVariation = layer.PositionVariation;
            int sizeMin = layer.SizeRange.Min;

            double width = layer.PlatformParams.Width;
            double depth = layer.PlatformParams.Depth;
            double centerThickness = layer.PlatformParams.CenterThickness;
            double edgeThickness = layer.PlatformParams.EdgeThickness;
            int interiorDensity = layer.PlatformParams.InteriorDensity;

            double baseRadius = sizeMin;

            spheres.Add(new CloudSphere
            {
                X = 0, Y = 0, Z = 0,
                Radius = (float)baseRadius,
                Depth = 0, Density = 1.0f,
                Archetype = CloudArchetype.Platform
            });

            var interiorPoints = CloudMath.FibonacciSpiral2D(interiorDensity);
            int spiralIdx = 0;

            for (int pi = 0; pi < interiorPoints.Length; pi++)
            {
                var pt = interiorPoints[pi];
                double px = pt.x * width * 0.5;
                double pz = pt.z * depth * 0.5;

                double dist = Math.Sqrt(
                    (px * px) / (width * width * 0.25) + (pz * pz) / (depth * depth * 0.25));
                double thickness = centerThickness * Math.Exp(-dist * dist * 3.0)
                                   + edgeThickness * dist;
                if (thickness < 0.2) continue;

                double yNoise = CloudMath.Perlin3D(px * 0.3, pz * 0.3, seed + 500, seed);
                double y = yNoise * thickness * 0.5
                           + jitter * baseRadius * CloudMath.Perlin3D(px, pz, seed, seed + 1);

                double rNoiseBase = Math.Pow(
                    (CloudMath.Perlin3D(px * 0.5, pz * 0.5, seed + 600 + spiralIdx, seed)
                     + 1.0) * 0.5, 1.8);
                double rNoiseMult = Math.Pow(
                    (CloudMath.Perlin3D(px * 0.5 + 70, pz * 0.5 + 70, seed + 650 + spiralIdx, seed + 1)
                     + 1.0) * 0.5, 1.5);
                double sizeBase = sizeMin + rNoiseBase * (layer.SizeRange.Max - sizeMin);
                double jitterFactor = 1.0 + jitter * (1.0 - clustering);
                double radius = sizeBase * (0.1 + rNoiseMult * 0.9) * jitterFactor;

                double densityVal = (0.3 + 0.7 * (1.0 - dist))
                                    * (clustering > 0.5 ? (0.7 + rNoiseBase * 0.3) : 1.0);

                if (densityVal < 0.1 || radius < 0.3) { spiralIdx++; continue; }

                double platOx = (rng.NextDouble() - 0.5) * 12.0 * radius * posVariation;
                double platOy = (rng.NextDouble() - 0.5) * 12.0 * radius * posVariation;
                double platOz = (rng.NextDouble() - 0.5) * 12.0 * radius * posVariation;

                spheres.Add(new CloudSphere
                {
                    X = (float)(px + platOx),
                    Y = (float)(y + platOy),
                    Z = (float)(pz + platOz),
                    Radius = (float)radius,
                    Depth = 0, Density = (float)densityVal,
                    Archetype = CloudArchetype.Platform
                });
                spiralIdx++;
            }

            return spheres;
        }

        private struct TreeFrame
        {
            public double X, Y, Z;
            public double DirX, DirY, DirZ;
            public double Radius;
            public int Depth;
            public int PathId;
            public double LengthMult;
        }

        private static List<CloudSphere> GenerateTreeLayer(CloudLayerConfig layer, ref DeterministicRandom rng)
        {
            var spheres = new List<CloudSphere>();
            int globalPathId = 0;

            int seed = layer.Seed;
            double jitter = layer.Jitter;
            double posVariation = layer.PositionVariation;
            int sizeMin = layer.SizeRange.Min;
            int sizeMax = layer.SizeRange.Max;

            double branchElongation = layer.TreeParams.BranchElongation;
            double taperRatio = layer.TreeParams.TaperRatio;
            double branchAngle = layer.TreeParams.BranchAngle * Math.PI / 180.0;
            double lengthFalloff = layer.TreeParams.LengthFalloff;
            double thicknessFalloff = layer.TreeParams.ThicknessFalloff;

            spheres.Add(new CloudSphere
            {
                X = 0, Y = 0, Z = 0,
                Radius = sizeMin,
                Depth = 0, Density = 1.0f,
                Archetype = CloudArchetype.Tree
            });

            var stack = new Stack<TreeFrame>();
            stack.Push(new TreeFrame
            {
                X = 0, Y = 0, Z = 0,
                DirX = 0, DirY = 1, DirZ = 0,
                Radius = sizeMin,
                Depth = 0, PathId = 0, LengthMult = 1.0
            });

            while (stack.Count > 0)
            {
                TreeFrame frame = stack.Pop();
                if (frame.Depth >= layer.TreeParams.MaxDepth) continue;
                if (frame.Radius < 0.5) continue;

                double dirLen = Math.Sqrt(
                    frame.DirX * frame.DirX + frame.DirY * frame.DirY + frame.DirZ * frame.DirZ);
                if (dirLen < 1e-15) continue;
                double dirNX = frame.DirX / dirLen;
                double dirNY = frame.DirY / dirLen;
                double dirNZ = frame.DirZ / dirLen;

                double extension = frame.Radius * branchElongation * frame.LengthMult;

                double a1 = CloudMath.Perlin3D(frame.X * 3, frame.Y * 3, frame.Z * 3, seed + frame.PathId)
                            * branchAngle;
                double a2 = CloudMath.Perlin3D(frame.X * 3, frame.Y * 3, frame.Z * 3 + 50, seed + frame.PathId + 1)
                            * branchAngle;
                double cos1 = Math.Cos(a1), sin1 = Math.Sin(a1);
                double cos2 = Math.Cos(a2), sin2 = Math.Sin(a2);

                double pdx = dirNX * cos1 - dirNY * sin1;
                double pdy = dirNX * sin1 + dirNY * cos1;
                double pdz = dirNZ;
                double pdx2 = pdx * cos2 + pdz * sin2;
                double pdy2 = pdy;
                double pdz2 = -pdx * sin2 + pdz * cos2;
                double pLen = Math.Sqrt(pdx2 * pdx2 + pdy2 * pdy2 + pdz2 * pdz2);
                if (pLen < 1e-15) continue;
                double perturbedDirX = pdx2 / pLen;
                double perturbedDirY = pdy2 / pLen;
                double perturbedDirZ = pdz2 / pLen;

                double jitterAngle = jitter * Math.PI
                                     * CloudMath.Perlin3D(frame.X, frame.Y, frame.PathId, seed);
                double jCos = Math.Cos(jitterAngle), jSin = Math.Sin(jitterAngle);
                double jDirX = jCos * perturbedDirX - jSin * perturbedDirY;
                double jDirY = jCos * perturbedDirY + jSin * perturbedDirX;
                double jDirZ = perturbedDirZ;

                double childPosX = frame.X + jDirX * extension
                                   + jitter * layer.TreeParams.BaseRadius * CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 50, seed);
                double childPosY = frame.Y + jDirY * extension
                                   + jitter * layer.TreeParams.BaseRadius * CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 60, seed);
                double childPosZ = frame.Z + jDirZ * extension
                                   + jitter * layer.TreeParams.BaseRadius * CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 70, seed);

                double sizeNoiseBase = Math.Pow(
                    (CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 80, seed) + 1.0) * 0.5, 1.8);
                double sizeNoiseMult = Math.Pow(
                    (CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 82, seed) + 1.0) * 0.5, 1.5);
                double radiusNoise = Math.Pow(
                    (CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 81, seed) + 1.0) * 0.5, 2.0);
                double szBase = sizeMin + sizeNoiseBase * (sizeMax - sizeMin);
                double childRadius = szBase * taperRatio * thicknessFalloff
                                     * (0.1 + sizeNoiseMult * 0.9)
                                     * (0.3 + radiusNoise * 0.7);
                double childDensity = 1.0 - (frame.Depth / (double)layer.TreeParams.MaxDepth) * 0.3;

                double treeOx = (rng.NextDouble() - 0.5) * 12.0 * childRadius * posVariation;
                double treeOy = (rng.NextDouble() - 0.5) * 12.0 * childRadius * posVariation;
                double treeOz = (rng.NextDouble() - 0.5) * 12.0 * childRadius * posVariation;

                spheres.Add(new CloudSphere
                {
                    X = (float)(childPosX + treeOx),
                    Y = (float)(childPosY + treeOy),
                    Z = (float)(childPosZ + treeOz),
                    Radius = (float)childRadius,
                    Depth = frame.Depth + 1, Density = (float)childDensity,
                    Archetype = CloudArchetype.Tree
                });

                stack.Push(new TreeFrame
                {
                    X = childPosX, Y = childPosY, Z = childPosZ,
                    DirX = perturbedDirX, DirY = perturbedDirY, DirZ = perturbedDirZ,
                    Radius = childRadius,
                    Depth = frame.Depth + 1,
                    PathId = frame.PathId,
                    LengthMult = frame.LengthMult * lengthFalloff
                });

                double val = (CloudMath.Perlin3D(
                                 frame.X * 2, frame.Y * 2, frame.Z * 2, seed + frame.PathId)
                             + 1.0) * 0.5;
                int lateralCount;
                if (val < 0.4) lateralCount = 0;
                else if (val < 0.75) lateralCount = 1;
                else if (val < 0.95) lateralCount = 2;
                else lateralCount = 3;

                for (int i = 0; i < lateralCount; i++)
                {
                    int lateralPathId = ++globalPathId;
                    double lateralAngle = (i / (double)Math.Max(lateralCount, 1)) * Math.PI * 2
                                          + CloudMath.Perlin3D(frame.PathId * 10, i * 5, seed, seed)
                                            * 0.5 * (1.0 + jitter);

                    double perpX = -dirNZ;
                    double perpZ = dirNX;
                    double latDirX = dirNX * Math.Cos(branchAngle)
                                     + perpX * Math.Sin(lateralAngle) * Math.Sin(branchAngle);
                    double latDirY = dirNY * Math.Cos(branchAngle)
                                     + Math.Sin(branchAngle) * 0.5;
                    double latDirZ = dirNZ * Math.Cos(branchAngle)
                                     + perpZ * Math.Sin(lateralAngle) * Math.Sin(branchAngle);

                    double latLen = Math.Sqrt(latDirX * latDirX + latDirY * latDirY + latDirZ * latDirZ);
                    if (latLen < 1e-15) continue;
                    latDirX /= latLen;
                    latDirY /= latLen;
                    latDirZ /= latLen;

                    double lateralRadius = childRadius * 0.7;
                    if (lateralRadius < 0.5) continue;

                    double lateralPosX = frame.X + latDirX * extension * 0.8;
                    double lateralPosY = frame.Y + latDirY * extension * 0.8;
                    double lateralPosZ = frame.Z + latDirZ * extension * 0.8;

                    double latOx = (rng.NextDouble() - 0.5) * 12.0 * lateralRadius * posVariation;
                    double latOy = (rng.NextDouble() - 0.5) * 12.0 * lateralRadius * posVariation;
                    double latOz = (rng.NextDouble() - 0.5) * 12.0 * lateralRadius * posVariation;

                    spheres.Add(new CloudSphere
                    {
                        X = (float)(lateralPosX + latOx),
                        Y = (float)(lateralPosY + latOy),
                        Z = (float)(lateralPosZ + latOz),
                        Radius = (float)lateralRadius,
                        Depth = frame.Depth + 1, Density = (float)(childDensity * 0.8),
                        Archetype = CloudArchetype.Tree
                    });

                    if (frame.Depth + 1 < layer.TreeParams.MaxDepth - 1)
                    {
                        stack.Push(new TreeFrame
                        {
                            X = lateralPosX, Y = lateralPosY, Z = lateralPosZ,
                            DirX = latDirX, DirY = latDirY, DirZ = latDirZ,
                            Radius = lateralRadius,
                            Depth = frame.Depth + 2,
                            PathId = lateralPathId,
                            LengthMult = frame.LengthMult * lengthFalloff * 0.8
                        });
                    }
                }
            }

            return spheres;
        }
    }
}
