// CloudTypes.cs v7.0
// Generated by Cloud Generator Visualizer
// DO NOT EDIT - Regenerate from visualizer

using System;
using System.Collections.Generic;

namespace ProjectC.CloudGenerator
{
    public enum CloudArchetype { Sphere, Column, Platform, Tree }

    [Serializable]
    public class SizeRange
    {
        public int Min = 5;
        public int Max = 20;
    }

    [Serializable]
    public class ColumnParams
    {
        public float Height = 40f;
        public float BaseRadius = 8f;
        public float TopRadius = 3f;
        public int Floors = 12;
        public int RingsPerFloor = 8;
        public float Wobble = 0.3f;
    }

    [Serializable]
    public class PlatformParams
    {
        public float Width = 50f;
        public float Depth = 50f;
        public float CenterThickness = 5f;
        public float EdgeThickness = 1f;
        public int InteriorDensity = 120;
        public int EdgeRings = 4;
    }

    [Serializable]
    public class TreeParams
    {
        public float BaseRadius = 8f;
        public int MaxDepth = 5;
        public float BranchElongation = 1.8f;
        public float TaperRatio = 0.8f;
        public float BranchAngle = 40f;
        public float BranchProbability = 0.5f;
        public float TrunkUpBias = 0.4f;
        public float LengthFalloff = 0.75f;
        public float ThicknessFalloff = 0.85f;
    }

    [Serializable]
    public class CloudLayerConfig
    {
        public CloudArchetype Archetype = CloudArchetype.Sphere;
        public bool Enabled = true;
        public float YOffset = 0f;
        public int Seed = 42;
        public float Density = 0.6f;
        public float Jitter = 0.3f;
        public float Clustering = 0.5f;
        public float PositionVariation = 0.5f;
        public int NoiseSalt = 0;
        public int CondensationLevel = -999;

        // Sphere params
        public float CloudSize = 80f;
        public int CascadeDepth = 3;
        public int BumpsPerLevel = 24;
        public float ChildRatio = 30f;
        public float SizeVariation = 1.0f;
        public int ParentCount = 1;
        public float EllipsoidY = 50f;
        public float EllipsoidXZ = 100f;
        public int MaxSphereCount = 5000;
        public float SphereCountScale = 1f;

        // Parent Mesh support
        public string ParentMeshPath = "";
        public float ParentMeshScaleX = 1f, ParentMeshScaleY = 1f, ParentMeshScaleZ = 1f;
        public float ParentMeshRotX = 0f, ParentMeshRotY = 0f, ParentMeshRotZ = 0f;
        public float ParentMeshOffsetX = 0f, ParentMeshOffsetY = 0f, ParentMeshOffsetZ = 0f;

        // Archetype-specific
        public SizeRange SizeRange = new SizeRange();
        public ColumnParams ColumnParams = new ColumnParams();
        public PlatformParams PlatformParams = new PlatformParams();
        public TreeParams TreeParams = new TreeParams();
    }

    public class CloudSphere
    {
        public float X, Y, Z;
        public float Radius;
        public int Depth;
        public float Density;
        public CloudArchetype Archetype;
        public int LayerIndex;
        public bool CutByCondensation;
    }

    [Serializable]
    public class CloudConfigExport
    {
        public List<CloudLayerConfig> layers;
        public string generatorVersion;
    }
}
