// CloudMath.cs v7.0
// Generated by Cloud Generator Visualizer
// DO NOT EDIT - Regenerate from visualizer

using System;

namespace ProjectC.CloudGenerator
{
    public static class CloudMath
    {
        public const double PHI = 1.6180339887498948482;

        public static int Hash3(int x, int y, int z, int seed)
        {
            long n64 = x + y * 57L + z * 131L + (long)seed * 123456789L;
            int n = unchecked((int)n64);
            n = (n << 13) ^ n;
            double dn = n;
            double d = dn * (dn * dn * 15731.0 + 789221.0) + 1376312589.0;
            const double two32 = 4294967296.0;
            double mod = d - two32 * Math.Floor(d / two32);
            if (mod >= 2147483648.0) mod -= two32;
            return ((int)mod) & 0x7FFFFFFF;
        }

        public static double Fade3(double t) => t * t * t * (t * (t * 6 - 15) + 10);
        public static double Lerp3(double a, double b, double t) => a + (b - a) * t;

        public static double Grad3(int h, double x, double y, double z)
        {
            int g = h & 15;
            double u = g < 8 ? x : y;
            double v = g < 4 ? y : (g == 12 || g == 14 ? x : z);
            return ((g & 1) != 0 ? -u : u) + ((g & 2) != 0 ? -v : v);
        }

        public static double Perlin3D(double x, double y, double z, int seed)
        {
            int xi = (int)Math.Floor(x) & 0xFF;
            int yi = (int)Math.Floor(y) & 0xFF;
            int zi = (int)Math.Floor(z) & 0xFF;
            double xf = x - Math.Floor(x);
            double yf = y - Math.Floor(y);
            double zf = z - Math.Floor(z);
            double u = Fade3(xf), v = Fade3(yf), w = Fade3(zf);
            int aaa = Hash3(xi, yi, zi, seed) % 12;
            int aba = Hash3(xi, yi + 1, zi, seed) % 12;
            int aab = Hash3(xi, yi, zi + 1, seed) % 12;
            int abb = Hash3(xi, yi + 1, zi + 1, seed) % 12;
            int baa = Hash3(xi + 1, yi, zi, seed) % 12;
            int bba = Hash3(xi + 1, yi + 1, zi, seed) % 12;
            int bab = Hash3(xi + 1, yi, zi + 1, seed) % 12;
            int bbb = Hash3(xi + 1, yi + 1, zi + 1, seed) % 12;
            double x1 = Lerp3(Grad3(aaa, xf, yf, zf), Grad3(baa, xf - 1, yf, zf), u);
            double x2 = Lerp3(Grad3(aba, xf, yf - 1, zf), Grad3(bba, xf - 1, yf - 1, zf), u);
            double y1 = Lerp3(x1, x2, v);
            double x3 = Lerp3(Grad3(aab, xf, yf, zf - 1), Grad3(bab, xf - 1, yf, zf - 1), u);
            double x4 = Lerp3(Grad3(abb, xf, yf - 1, zf - 1), Grad3(bbb, xf - 1, yf - 1, zf - 1), u);
            double y2 = Lerp3(x3, x4, v);
            return Lerp3(y1, y2, w);
        }

        public static double Fbm(double x, double y, double z, int octaves = 5, double persistence = 0.5, double lacunarity = 2.0, int seed = 0)
        {
            double value = 0, amplitude = 1, frequency = 1, maxValue = 0;
            for (int i = 0; i < octaves; i++)
            {
                value += amplitude * Perlin3D(x * frequency, y * frequency, z * frequency, seed + i);
                maxValue += amplitude;
                amplitude *= persistence;
                frequency *= lacunarity;
            }
            return value / maxValue;
        }

        public static double Worley3D(double x, double y, double z, double freq, int seed = 0)
        {
            int ix = (int)Math.Floor(x * freq);
            int iy = (int)Math.Floor(y * freq);
            int iz = (int)Math.Floor(z * freq);
            double minDist = 1e9;
            for (int dx = -1; dx <= 1; dx++)
            {
                for (int dy = -1; dy <= 1; dy++)
                {
                    for (int dz = -1; dz <= 1; dz++)
                    {
                        int cx = ix + dx;
                        int cy = iy + dy;
                        int cz = iz + dz;
                        int h = ((cx * 12345) ^ (cy * 67890) ^ (cz * 13579)) & 0x7FFFFFFF;
                        h += (int)((long)seed * 123456789);
                        double sx = (h % 1000) / 1000.0;
                        double sy = ((h / 1000) % 1000) / 1000.0;
                        double sz = ((h / 1000000) % 1000) / 1000.0;
                        double dx2 = x * freq - (cx + sx);
                        double dy2 = y * freq - (cy + sy);
                        double dz2 = z * freq - (cz + sz);
                        double dist = Math.Sqrt(dx2 * dx2 + dy2 * dy2 + dz2 * dz2);
                        if (dist < minDist) minDist = dist;
                    }
                }
            }
            return minDist;
        }

        public static double InvertedWorley(double x, double y, double z, double freq, int seed = 0) => 1.0 - Math.Min(Worley3D(x, y, z, freq, seed), 1.0);

        public static (double x, double y, double z)[] FibonacciSphere(double cx, double cy, double cz, double rx, double ry, double rz, int numPoints)
        {
            var points = new (double x, double y, double z)[numPoints];
            double angleInc = Math.PI * 2 * PHI;
            for (int i = 0; i < numPoints; i++)
            {
                double t = i / (double)numPoints;
                double inclination = Math.Acos(1 - 2 * t);
                double azimuth = angleInc * i;
                double sx = Math.Sin(inclination) * Math.Cos(azimuth);
                double sy = Math.Sin(inclination) * Math.Sin(azimuth);
                double sz = Math.Cos(inclination);
                points[i] = (cx + sx * rx, cy + sy * ry, cz + sz * rz);
            }
            return points;
        }

        public static (double x, double z)[] FibonacciSpiral2D(int count)
        {
            var points = new (double x, double z)[count];
            double angleInc = Math.PI * 2 * PHI;
            for (int i = 0; i < count; i++)
            {
                double r = Math.Sqrt(i / (double)count);
                double theta = angleInc * i;
                points[i] = (r * Math.Cos(theta), r * Math.Sin(theta));
            }
            return points;
        }

        public static (double x, double y, double z) PerturbDir(double nx, double ny, double nz, double px, double py, double pz, double strength, int seed)
        {
            double a1 = Perlin3D(px * 10, py * 10, pz * 10, seed) * strength;
            double a2 = Perlin3D(px * 10, py * 10, pz * 10 + 50, seed + 1) * strength;
            double cos1 = Math.Cos(a1), sin1 = Math.Sin(a1);
            double cos2 = Math.Cos(a2), sin2 = Math.Sin(a2);
            double nx2 = nx * cos1 - ny * sin1;
            double ny2 = nx * sin1 + ny * cos1;
            double nz2 = nz;
            double nx3 = nx2 * cos2 + nz2 * sin2;
            double ny3 = ny2;
            double nz3 = -nx2 * sin2 + nz2 * cos2;
            double len = Math.Sqrt(nx3 * nx3 + ny3 * ny3 + nz3 * nz3);
            if (len == 0) len = 1;
            return (nx3 / len, ny3 / len, nz3 / len);
        }
    }
}
