using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Threading;
using UnityEditor;
using UnityEngine;
using ProjectC.World.FloatingOrigin;
using ProjectC.World.FloatingOrigin.Network;
using ProjectC.World.FloatingOrigin.Persistence;

namespace ProjectC.EditorTools.FloatingOrigin
{
    /// <summary>Pure capture facts + controllable trusted source + actual B repository against memory storage. No live NGO actors or disk.</summary>
    public static class ValidateGlobalCheckpointCapture
    {
        [Serializable] public sealed class Report { public int passed; public int failed; public string[] checks; public string[] failures; }
        [MenuItem("ProjectC/World/Floating Origin/Validate Authoritative Checkpoint Capture")]
        public static void Execute() { var r = Run(); if (r.failed != 0) throw new InvalidOperationException(JsonUtility.ToJson(r, true)); Debug.Log($"[T-FO05C] {r.passed} pure checks PASS; native source UNTESTED."); }
        public static Report Run()
        {
            if (EditorApplication.isCompiling || EditorApplication.isPlayingOrWillChangePlaymode) throw new InvalidOperationException("Stable Edit Mode required.");
            var good = new List<string>(); var bad = new List<string>();
            void Check(string n, Action a) { try { a(); good.Add(n); } catch (Exception e) { bad.Add(n + ": " + e.GetType().Name + ": " + e.Message); } }
            Check("Accepted owner world sample validates", () => Valid(State()));
            Check("Server-authority world sample validates", () => Valid(State(Entry(authority: GlobalMotionAuthority.Server, publisher: 0))));
            Check("Actual NGO object and owner ID zero are allowed with explicit identity", () => Valid(State(Entry(owner: 0, objectId: 0, publisher: 0))));
            Check("Null scope and zero session/run/source are rejected", () => { Invalid(null); Invalid(new GlobalPlayerCaptureSnapshot(Guid.Empty, 7, 2, 100.5, new[] { Entry() })); Invalid(new GlobalPlayerCaptureSnapshot(Id(1), 0, 2, 100.5, new[] { Entry() })); Invalid(new GlobalPlayerCaptureSnapshot(Id(1), 7, 0, 100.5, new[] { Entry() })); });
            Check("No players does not fabricate an empty checkpoint", () => Invalid(State(Array.Empty<GlobalPlayerCaptureEntry>())));
            Check("Invalid explicit max age rejected", () => { foreach (double age in new[] { 0d, -1d, double.NaN, double.PositiveInfinity, 61d }) Require(!GlobalPlayerCapturePolicy.Validate(State(), age, out _)); });
            Check("Exact freshness boundary accepted and expired sample rejected", () => { Valid(State(Entry(), now: 102)); Invalid(State(Entry(), now: 102.001)); });
            Check("Future sample or invalid server clock rejected", () => { Invalid(State(Entry(), now: 99)); Invalid(State(Entry(), now: double.NaN)); });
            Check("Wrong motion session rejected", () => Invalid(State(Entry(session: 8))));
            Check("Missing persistent identity and lease rejected", () => { Invalid(State(Entry(playerId: ""))); var e = Entry(); Invalid(State(new GlobalPlayerCaptureEntry(e.PlayerId, Guid.Empty, e.OwnerClientId, e.Sample, e.Authority, e.PublisherClientId, false))); });
            Check("Duplicate durable player identity rejected", () => Invalid(State(new[] { Entry(), Entry(owner: 2, objectId: 2, publisher: 2, lease: Id(12)) })));
            Check("Duplicate owner object or identity lease rejected", () => { Invalid(State(new[] { Entry(), Entry(playerId: "account-b", objectId: 2, lease: Id(12)) })); Invalid(State(new[] { Entry(), Entry(playerId: "account-b", owner: 2, publisher: 2, lease: Id(12)) })); Invalid(State(new[] { Entry(), Entry(playerId: "account-b", owner: 2, objectId: 2, publisher: 2) })); });
            Check("Ship affinity and parent-local states require later bridge", () => { Invalid(State(Entry(inShip: true))); var b = Binding(); b.Space = MotionCoordinateSpace.ParentLocal; b.ParentNetworkObjectId = 999; b.ParentSpawnGeneration = 1; var s = GlobalMotionSnapshot.CreateParentLocal(b, 10, 100, Vector3.one, Quaternion.identity, Vector3.one); Invalid(State(new GlobalPlayerCaptureEntry("account-a", Id(11), 1, s, GlobalMotionAuthority.Owner, 1, false))); });
            Check("Owner/server publisher mismatch rejected", () => { Invalid(State(Entry(publisher: 2))); Invalid(State(Entry(authority: GlobalMotionAuthority.Server, publisher: 1))); Invalid(State(Entry(authority: (GlobalMotionAuthority)99))); });
            Check("Snapshot malformed version and nonfinite point rejected", () => { var e = Entry(); var s = e.Sample; s.Version = 999; Invalid(State(WithSample(e, s))); s = e.Sample; s.WorldPosition.X = double.NaN; Invalid(State(WithSample(e, s))); });
            Check("Actor lifetime ignores authority but not respawn/session/object", () => { var a = Binding(); var b = a; b.AuthorityGeneration++; Require(GlobalPlayerCapturePolicy.SameActorLifetime(a, b)); b = a; b.SpawnGeneration++; Require(!GlobalPlayerCapturePolicy.SameActorLifetime(a, b)); b = a; b.SessionId++; Require(!GlobalPlayerCapturePolicy.SameActorLifetime(a, b)); b = a; b.NetworkObjectId++; Require(!GlobalPlayerCapturePolicy.SameActorLifetime(a, b)); });
            Check("Exact evidence comparison is order independent", () => { var a = Entry(); var b = Entry("account-b", 2, 2, 2, Id(12)); Require(GlobalPlayerCapturePolicy.SameEvidence(State(new[] { a, b }), State(new[] { b, a }), 2, out _)); });
            Check("Normal newer motion does not starve point-in-time commit", () => Require(GlobalPlayerCapturePolicy.CanPublishCaptured(State(), State(Entry(sequence: 11, sampleTime: 101, x: 999), now: 101.5), 2, out _)));
            Check("Captured point expires even if newest sample is fresh", () => Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(State(), State(Entry(sequence: 11, sampleTime: 103), now: 103.1), 2, out _)));
            Check("Sequence wrap is accepted but regression and half-range ambiguity are not", () => { Require(GlobalPlayerCapturePolicy.CanPublishCaptured(State(Entry(sequence: uint.MaxValue)), State(Entry(sequence: 0, sampleTime: 101), now: 101), 2, out _)); Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(State(), State(Entry(sequence: 9, sampleTime: 101), now: 101), 2, out _)); Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(State(Entry(sequence: 0)), State(Entry(sequence: 0x80000000, sampleTime: 101), now: 101), 2, out _)); });
            Check("Same sequence cannot rewrite pose or time", () => { Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(State(), State(Entry(x: 9)), 2, out _)); Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(State(), State(Entry(sampleTime: 100.2)), 2, out _)); });
            Check("New sequence cannot regress accepted server time", () => Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(State(), State(Entry(sequence: 11, sampleTime: 99.9)), 2, out _)));
            Check("Authority or discontinuity transition invalidates prepared capture", () => { var e = Entry(); var s = e.Sample; s.Binding.AuthorityGeneration++; Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(State(), State(WithSample(e, s)), 2, out _)); s = e.Sample; s.Binding.DiscontinuityGeneration++; Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(State(), State(WithSample(e, s)), 2, out _)); });
            Check("Source run session roster or identity-lease replacement invalidates capture", () => { var old = State(); Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(old, new GlobalPlayerCaptureSnapshot(Id(2), 7, 2, 100.5, old.Entries), 2, out _)); Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(old, new GlobalPlayerCaptureSnapshot(Id(1), 7, 3, 100.5, old.Entries), 2, out _)); Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(old, State(Entry(lease: Id(99))), 2, out _)); Require(!GlobalPlayerCapturePolicy.CanPublishCaptured(old, State(new[] { Entry(), Entry("account-b", 2, 2, 2, Id(12)) }), 2, out _)); });
            Check("Captured struct and collection cannot be changed by caller", () => { var e = Entry(); var s = State(e); var copy = e.Sample; copy.WorldPosition.X = 0; Require(e.Sample.WorldPosition.X != 0); Throws(() => ((IList<GlobalPlayerCaptureEntry>)s.Entries).Clear()); });
            Check("Owner admission rejection never becomes latest accepted checkpoint", () => { var e = Entry(); var ingress = new GlobalMotionAdmission(); ingress.Begin(1, e.Sample, 100); var next = e.Sample; next.Sequence = 11; next.SampleTime = 100.1; next.WorldPosition = new GlobalPosition(888, 2, 3); Require(!ingress.TryAccept(1, next, 100.2, _ => false, out _, out _) && GlobalPlayerCapturePolicy.SameAcceptedSample(ingress.Latest, e.Sample)); next.Sequence = 12; Require(ingress.TryAccept(1, next, 100.3, _ => true, out var accepted, out _) && accepted.SampleTime == 100.3 && accepted.WorldPosition.X == 888); });
            Check("Prepare performs no repository writes", () => { var c = new Case(); Prepare(c); Require(c.Store.Stages == 0 && c.Store.Publications == 0); });
            Check("Accepted global doubles survive prepare merge and B commit", () => { var c = new Case(); var b = Prepare(c); Applied(c.Capture.TryCommit(b)); var saved = c.Repository.Inspect().Snapshot.Players[0]; Require(saved.Position == b.Source.Entries[0].Sample.WorldPosition && saved.PlayerId == "account-a" && saved.SavedAtUnix == 200); });
            Check("Offline player and ship-affinity checkpoint retained verbatim", () => { var c = new Case(); var offline = new GlobalPlayerPositionRecord("offline", new GlobalPosition(7, 8, 9), true, "ship-a", 999); Applied(c.Repository.TryCommit(c.Repository.Inspect(), new[] { offline })); var b = Prepare(c); Applied(c.Capture.TryCommit(b)); var saved = c.Repository.Inspect().Snapshot; Require(saved.Players.Count == 2); var p = saved.Players[1]; Require(p.PlayerId == "offline" && p.InShip && p.ShipPersistentId == "ship-a" && p.SavedAtUnix == 999 && p.Position == offline.Position); });
            Check("Capture updates existing ID once and does not persist ephemeral IDs", () => { var c = new Case(); Applied(c.Repository.TryCommit(c.Repository.Inspect(), new[] { new GlobalPlayerPositionRecord("account-a", GlobalPosition.Zero, false, "", 100) })); var b = Prepare(c); Applied(c.Capture.TryCommit(b)); Require(c.Repository.Inspect().Snapshot.Players.Count == 1); Require(GlobalPlayerPositionCodec.TryEncode(b.Players[0], out var json, out _) && !json.Contains("ClientId") && !json.Contains("SessionId") && !json.Contains("IdentityLease") && !json.Contains("FrameId")); });
            Check("Bad clock does not overwrite saved newer state", () => { var c = new Case(); Applied(c.Repository.TryCommit(c.Repository.Inspect(), new[] { new GlobalPlayerPositionRecord("account-a", GlobalPosition.Zero, false, "", 300) })); Require(!c.Capture.TryPrepare(c.Repository.Inspect(), 200, 2, out var b, out _) && b == null && c.Store.Stages == 1); });
            Check("Invalid timestamp and freshness policy do not create batch", () => { var c = new Case(); Require(!c.Capture.TryPrepare(c.Repository.Inspect(), -1, 2, out _, out _)); Require(!c.Capture.TryPrepare(c.Repository.Inspect(), 200, double.NaN, out _, out _)); });
            Check("Pending blocked storage cannot be treated as Empty", () => { var c = new Case(); c.Store.Pending = new byte[] { 1 }; Require(!c.Capture.TryPrepare(c.Repository.Inspect(), 200, 2, out var b, out _) && b == null); });
            Check("Unavailable source rejects entire capture", () => { var c = new Case(); c.Source.FailCapture = true; Require(!c.Capture.TryPrepare(c.Repository.Inspect(), 200, 2, out _, out _) && c.Store.Stages == 0); });
            Check("Malformed/duplicate capture cannot partially merge", () => { var c = new Case(); c.Source.Current = State(new[] { Entry(), Entry() }); Require(!c.Capture.TryPrepare(c.Repository.Inspect(), 200, 2, out var b, out _) && b == null && c.Store.Stages == 0); });
            Check("Source changes during prepare yield no batch", () => { var c = new Case(); c.Source.OnCurrent = () => c.Source.Current = State(Entry(lease: Id(99))); Require(!c.Capture.TryPrepare(c.Repository.Inspect(), 200, 2, out var b, out _) && b == null); });
            Check("Foreign and reused batches are rejected", () => { var a = new Case(); var b = Prepare(a); var other = new GlobalPlayerCheckpointCapture(a.Source, a.Repository); Require(other.TryCommit(b).Status == CheckpointTransactionStatus.NotApplied); Applied(a.Capture.TryCommit(b)); Require(a.Capture.TryCommit(b).Status == CheckpointTransactionStatus.NotApplied && a.Store.Publications == 1); });
            Check("Changed connection identity before commit produces no staging", () => { var c = new Case(); var b = Prepare(c); c.Source.Current = State(Entry(lease: Id(99))); Require(c.Capture.TryCommit(b).Status == CheckpointTransactionStatus.NotApplied && c.Store.Stages == 0); });
            Check("World reset or roster change before commit rejects", () => { var c = new Case(); var b = Prepare(c); c.Source.Current = State(Entry(session: 8), session: 8); Require(c.Capture.TryCommit(b).Status == CheckpointTransactionStatus.NotApplied && c.Store.Stages == 0); });
            Check("Moving player can commit previously captured fresh global point", () => { var c = new Case(); var b = Prepare(c); c.Source.Current = State(Entry(sequence: 11, sampleTime: 101, x: 999), now: 101.1); Applied(c.Capture.TryCommit(b)); Require(c.Repository.Inspect().Snapshot.Players[0].Position == b.Source.Entries[0].Sample.WorldPosition); });
            Check("Newer ordinary motion during staging does not starve publication", () => { var c = new Case(); var b = Prepare(c); c.Store.AfterStage = () => c.Source.Current = State(Entry(sequence: 11, sampleTime: 101, x: 999), now: 101.1); Applied(c.Capture.TryCommit(b)); Require(c.Repository.Inspect().Snapshot.Players[0].Position.X != 999); });
            Check("Capture expiry during staging is surfaced as Pending, not automatically deleted", () => { var c = new Case(); var b = Prepare(c); c.Store.AfterStage = () => c.Source.Current = State(Entry(sequence: 11, sampleTime: 103), now: 103.1); var r = c.Capture.TryCommit(b); Require(r.Status == CheckpointTransactionStatus.NotApplied && r.Observation.Status == CheckpointStoreStatus.Pending && c.Store.Pending != null && c.Store.Primary == null && c.Store.Publications == 0); });
            Check("Teleport during staging blocks publication and requires explicit quarantine", () => { var c = new Case(); var b = Prepare(c); c.Store.AfterStage = () => { var e = Entry(); var s = e.Sample; s.Binding.DiscontinuityGeneration++; c.Source.Current = State(WithSample(e, s)); }; var r = c.Capture.TryCommit(b); Require(r.Status == CheckpointTransactionStatus.NotApplied && r.Observation.Status == CheckpointStoreStatus.Pending); Applied(c.Repository.TryQuarantinePending(r.Observation)); Require(c.Store.Quarantine.Count == 1); });
            Check("Consumed failed batch cannot be retried after source repair", () => { var c = new Case(); var b = Prepare(c); c.Source.FailCurrent = true; Require(c.Capture.TryCommit(b).Status == CheckpointTransactionStatus.NotApplied); c.Source.FailCurrent = false; Require(c.Capture.TryCommit(b).Status == CheckpointTransactionStatus.NotApplied && c.Store.Stages == 0); });
            Check("Store CAS conflict never retries against a new head", () => { var c = new Case(); var b = Prepare(c); Applied(c.Repository.TryCommit(c.Repository.Inspect(), new[] { new GlobalPlayerPositionRecord("offline", GlobalPosition.Zero, false, "", 1) })); Require(c.Capture.TryCommit(b).Status == CheckpointTransactionStatus.Conflict && c.Store.Stages == 1); });
            Check("Guard executes before stage and after stage", () => { var c = new Case(); var b = Prepare(c); int previous = c.Source.CurrentCalls; Applied(c.Capture.TryCommit(b)); Require(c.Source.CurrentCalls - previous == 3); });
            Check("Direct B guard false before stage changes no payload", () => { var c = new Case(); var r = c.Repository.TryCommit(c.Repository.Inspect(), new[] { Persistent() }, false, () => false); Require(r.Status == CheckpointTransactionStatus.NotApplied && c.Store.Stages == 0); });
            Check("Direct B guard exception before stage changes no payload", () => { var c = new Case(); var r = c.Repository.TryCommit(c.Repository.Inspect(), new[] { Persistent() }, false, () => throw new InvalidOperationException()); Require(r.Status == CheckpointTransactionStatus.NotApplied && c.Store.Stages == 0); });
            Check("Direct B guard exception after stage retains pending", () => { var c = new Case(); int calls = 0; var r = c.Repository.TryCommit(c.Repository.Inspect(), new[] { Persistent() }, false, () => ++calls == 1 ? true : throw new InvalidOperationException()); Require(r.Status == CheckpointTransactionStatus.NotApplied && c.Store.Pending != null && c.Store.Publications == 0); });
            Check("Storage mutation inside pre-stage guard is a conflict", () => { var c = new Case(); var r = c.Repository.TryCommit(c.Repository.Inspect(), new[] { Persistent() }, false, () => { c.Store.Pending = new byte[] { 1 }; return true; }); Require(r.Status == CheckpointTransactionStatus.Conflict && c.Store.Stages == 0); });
            Check("Storage mutation inside final guard blocks publication", () => { var c = new Case(); int calls = 0; var r = c.Repository.TryCommit(c.Repository.Inspect(), new[] { Persistent() }, false, () => { if (++calls == 2) c.Store.Pending = new byte[] { 9 }; return true; }); Require(r.Status == CheckpointTransactionStatus.NotApplied && c.Store.Publications == 0); });
            Check("Reentrant repository call from guard is rejected by storage lease", () => { var c = new Case(); var o = c.Repository.Inspect(); CheckpointTransactionResult nested = null; Applied(c.Repository.TryCommit(o, new[] { Persistent() }, false, () => { nested = c.Repository.TryCommit(o, new[] { Persistent() }); return true; })); Require(nested.Status == CheckpointTransactionStatus.Unavailable); });
            Check("Reentrant capture commit cannot publish twice", () => { var c = new Case(); var b = Prepare(c); CheckpointTransactionResult nested = null; c.Source.OnCurrent = () => nested = c.Capture.TryCommit(b); Applied(c.Capture.TryCommit(b)); Require(nested.Status == CheckpointTransactionStatus.NotApplied && c.Store.Publications == 1); });
            Check("Owner-thread mismatch rejects before source or storage access", () => { var c = new Case(); bool prepared = true; Exception fault = null; var t = new Thread(() => { try { prepared = c.Capture.TryPrepare(null, 200, 2, out _, out _); } catch (Exception e) { fault = e; } }); t.Start(); t.Join(); Require(fault == null && !prepared && c.Source.CaptureCalls == 0 && c.Store.Stages == 0); });
            Check("All pending/unknown player situations surface source refusal instead of being skipped", () => { var c = new Case(); c.Source.FailCapture = true; c.Source.Current = State(Entry("account-b", 2, 2, 2, Id(12))); Require(!c.Capture.TryPrepare(c.Repository.Inspect(), 200, 2, out var b, out _) && b == null); });
            Check("Prepared durable collection is immutable", () => { var c = new Case(); var b = Prepare(c); Throws(() => ((IList<GlobalPlayerPositionRecord>)b.Players).Clear()); });
            Check("Compiled native read seams and concrete source exist without instantiation", () => { Require(typeof(GlobalMotionReplicator).GetMethod("TryReadServerAcceptedMotion") != null && typeof(GlobalMotionWorld).GetMethod("TryGetServerCheckpointScope") != null && typeof(IGlobalPlayerCheckpointSource).IsAssignableFrom(typeof(GlobalMotionPlayerCheckpointSource))); });
            Check("No new automatic Unity lifecycle component or persisted frame identity", () => Require(!typeof(UnityEngine.Object).IsAssignableFrom(typeof(GlobalMotionPlayerCheckpointSource)) && !typeof(UnityEngine.Object).IsAssignableFrom(typeof(GlobalPlayerCheckpointCapture)) && typeof(GlobalPlayerPositionRecord).GetProperty("OwnerClientId") == null));
            return new Report { passed = good.Count, failed = bad.Count, checks = good.ToArray(), failures = bad.ToArray() };
        }
        private static Guid Id(int i) => Guid.ParseExact(i.ToString("x32"), "N");
        private static MotionStreamBinding Binding(ulong session = 7, ulong objectId = 0) => new MotionStreamBinding { SessionId = session, NetworkObjectId = objectId, SpawnGeneration = 2, AuthorityGeneration = 1, DiscontinuityGeneration = 1, Space = MotionCoordinateSpace.World };
        private static GlobalPlayerCaptureEntry Entry(string playerId = "account-a", ulong owner = 1, ulong objectId = 0, ulong publisher = 1, Guid? lease = null, ulong session = 7, uint sequence = 10, double sampleTime = 100, double x = 56500.000000123, bool inShip = false, GlobalMotionAuthority authority = GlobalMotionAuthority.Owner)
            => new GlobalPlayerCaptureEntry(playerId, lease ?? Id(11), owner, GlobalMotionSnapshot.CreateWorld(Binding(session, objectId), sequence, sampleTime, new GlobalPosition(x, 2, 3), Quaternion.identity, Vector3.one), authority, publisher, inShip);
        private static GlobalPlayerCaptureEntry WithSample(GlobalPlayerCaptureEntry e, GlobalMotionSnapshot s) => new GlobalPlayerCaptureEntry(e.PlayerId, e.IdentityLease, e.OwnerClientId, s, e.Authority, e.PublisherClientId, e.InShip);
        private static GlobalPlayerCaptureSnapshot State(GlobalPlayerCaptureEntry entry = null, double now = 100.5, ulong session = 7) => State(new[] { entry ?? Entry() }, now, session);
        private static GlobalPlayerCaptureSnapshot State(IReadOnlyList<GlobalPlayerCaptureEntry> entries, double now = 100.5, ulong session = 7) => new GlobalPlayerCaptureSnapshot(Id(1), session, 2, now, entries);
        private static GlobalPlayerPositionRecord Persistent() => new GlobalPlayerPositionRecord("account-a", GlobalPosition.Zero, false, "", 200);
        private static void Valid(GlobalPlayerCaptureSnapshot s) => Require(GlobalPlayerCapturePolicy.Validate(s, 2, out var e), e);
        private static void Invalid(GlobalPlayerCaptureSnapshot s) => Require(!GlobalPlayerCapturePolicy.Validate(s, 2, out _));
        private static GlobalPlayerCheckpointCaptureBatch Prepare(Case c) { Require(c.Capture.TryPrepare(c.Repository.Inspect(), 200, 2, out var b, out var e), e); return b; }
        private static void Applied(CheckpointTransactionResult r) => Require(r.Status == CheckpointTransactionStatus.Applied, r.Status + ": " + r.Error);
        private sealed class Case
        {
            public readonly Source Source = new Source(); public readonly MemoryStorage Store = new MemoryStorage();
            public readonly GlobalPlayerCheckpointRepository Repository; public readonly GlobalPlayerCheckpointCapture Capture;
            public Case() { Repository = new GlobalPlayerCheckpointRepository("world-a", Store); Capture = new GlobalPlayerCheckpointCapture(Source, Repository); }
        }
        private sealed class Source : IGlobalPlayerCheckpointSource
        {
            public GlobalPlayerCaptureSnapshot Current = State(); public bool FailCapture, FailCurrent; public Action OnCurrent; public int CaptureCalls, CurrentCalls;
            private readonly HashSet<GlobalPlayerCaptureSnapshot> _issued = new HashSet<GlobalPlayerCaptureSnapshot>();
            public bool TryCapture(double maxAge, out GlobalPlayerCaptureSnapshot s, out string e) { CaptureCalls++; s = null; e = "fixture_source_unready"; if (FailCapture) return false; s = Current; _issued.Add(s); return GlobalPlayerCapturePolicy.Validate(s, maxAge, out e); }
            public bool IsCurrent(GlobalPlayerCaptureSnapshot s, double maxAge, out string e) { CurrentCalls++; e = "fixture_scope_changed"; OnCurrent?.Invoke(); return !FailCurrent && _issued.Contains(s) && GlobalPlayerCapturePolicy.CanPublishCaptured(s, Current, maxAge, out e); }
        }
        private sealed class MemoryStorage : IGlobalPlayerCheckpointStorage
        {
            public byte[] Primary, Backup, Pending; public readonly Dictionary<string, byte[]> Quarantine = new Dictionary<string, byte[]>(); public int Stages, Publications; public Action AfterStage;
            private bool _held;
            public IDisposable AcquireLease() { if (_held) throw new IOException("lease_held"); _held = true; return new Release(this); }
            public byte[] Read(CheckpointSlot slot, int max) { Guard(); var b = slot == CheckpointSlot.Primary ? Primary : slot == CheckpointSlot.Backup ? Backup : Pending; if (b != null && b.Length > max) throw new IOException("oversized"); return Clone(b); }
            public void WritePendingNew(byte[] b) { Guard(); if (Pending != null) throw new IOException("pending_exists"); Stages++; Pending = Clone(b); AfterStage?.Invoke(); }
            public void PublishPending(bool replace, string q) { Guard(); Publications++; if (Pending == null || (Primary != null) != replace) throw new IOException("bad_publish"); if (replace) { if (q == null) Backup = Clone(Primary); else Quarantine.Add(q, Clone(Primary)); } Primary = Pending; Pending = null; }
            public void QuarantinePending(string q) { Guard(); if (Pending == null) throw new IOException("missing_pending"); Quarantine.Add(q, Clone(Pending)); Pending = null; }
            public byte[] ReadQuarantine(string q, int max) { Guard(); return Quarantine.TryGetValue(q, out var b) ? Clone(b) : null; }
            private static byte[] Clone(byte[] b) => b == null ? null : (byte[])b.Clone();
            private void Guard() { if (!_held) throw new InvalidOperationException("lease_required"); }
            private sealed class Release : IDisposable { private MemoryStorage _s; public Release(MemoryStorage s) { _s = s; } public void Dispose() { if (_s != null) _s._held = false; _s = null; } }
        }
        private static void Throws(Action a) { bool thrown = false; try { a(); } catch (Exception) { thrown = true; } Require(thrown); }
        private static void Require(bool value, string error = null) { if (!value) throw new InvalidOperationException(error ?? "Assertion failed."); }
    }
}
