// CloudGeneratorWindow.cs v7.0
// Generated by Cloud Generator Visualizer
// DO NOT EDIT - Regenerate from visualizer

using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

namespace ProjectC.CloudGenerator.Editor
{
    public class CloudGeneratorWindow : EditorWindow
    {
        private List<CloudLayerConfig> layers;
        private Vector2 scrollPos;
        private List<CloudSphere> lastResult;

        [MenuItem("Tools/Project C/Cloud Generator")]
        public static void ShowWindow()
        {
            var window = GetWindow<CloudGeneratorWindow>("Cloud Generator");
            window.minSize = new Vector2(300, 400);
            window.Show();
        }

        private void OnEnable()
        {
            layers = new List<CloudLayerConfig>();
        }

        private void OnGUI()
        {
            scrollPos = EditorGUILayout.BeginScrollView(scrollPos);

            EditorGUILayout.Space(10);
            EditorGUILayout.LabelField("Cloud Generator v7.0", EditorStyles.boldLabel);
            EditorGUILayout.Space(5);

            if (GUILayout.Button("Generate", GUILayout.Height(30)))
            {
                lastResult = CloudGenerator.Generate(layers);
                Debug.Log($"Generated {lastResult.Count} spheres");

                GameObject cloudParent = new GameObject("CloudGenerator_Parent");
                cloudParent.transform.position = Vector3.zero;

                for (int i = 0; i < lastResult.Count; i++)
                {
                    CloudSphere s = lastResult[i];
                    GameObject sphere = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                    sphere.name = $"Sphere_{i}";
                    sphere.transform.parent = cloudParent.transform;
                    sphere.transform.position = new Vector3(s.X, s.Y, s.Z);
                    sphere.transform.localScale = Vector3.one * s.Radius * 2;
                }

                Selection.activeObject = cloudParent;
                EditorGUIUtility.PingObject(cloudParent);
            }

            if (lastResult != null)
            {
                EditorGUILayout.LabelField($"Spheres: {lastResult.Count}", EditorStyles.label);
            }

            EditorGUILayout.Space(5);
            EditorGUILayout.LabelField("Config", EditorStyles.boldLabel);
            EditorGUILayout.BeginHorizontal();
            if (GUILayout.Button("Load Config"))
            {
                string path = EditorUtility.OpenFilePanel("Load Cloud Config", "", "json");
                if (!string.IsNullOrEmpty(path))
                {
                    string json = System.IO.File.ReadAllText(path);
                    var config = JsonUtility.FromJson<CloudConfigExport>(json);
                    if (config != null && config.layers != null)
                    {
                        layers = config.layers;
                        Debug.Log($"Loaded {layers.Count} layers from config");
                        Repaint();
                    }
                }
            }
            if (GUILayout.Button("Save Config"))
            {
                string path = EditorUtility.SaveFilePanel("Save Cloud Config", "", "cloud_config", "json");
                if (!string.IsNullOrEmpty(path))
                {
                    var config = new CloudConfigExport { layers = layers };
                    string json = JsonUtility.ToJson(config);
                    System.IO.File.WriteAllText(path, json);
                }
            }
            EditorGUILayout.EndHorizontal();

            EditorGUILayout.Space(10);
            EditorGUILayout.LabelField("Layers", EditorStyles.boldLabel);

            for (int i = 0; i < layers.Count; i++)
            {
                EditorGUILayout.BeginVertical("box");
                DrawLayerInspector(layers[i], i);
                EditorGUILayout.EndVertical();
            }

            EditorGUILayout.BeginHorizontal();
            if (GUILayout.Button("+ Add Layer"))
            {
                layers.Add(new CloudLayerConfig
                {
                    Archetype = CloudArchetype.Sphere,
                    Seed = Random.Range(1, 99999),
                    Density = 0.6f,
                    SizeRange = new SizeRange { Min = 5, Max = 20 }
                });
            }
            if (GUILayout.Button("Clear All"))
            {
                layers.Clear();
            }
            EditorGUILayout.EndHorizontal();

            EditorGUILayout.EndScrollView();
        }

        private void DrawLayerInspector(CloudLayerConfig layer, int index)
        {
            EditorGUI.indentLevel++;
            layer.Enabled = EditorGUILayout.Toggle("Enabled", layer.Enabled);
            layer.Archetype = (CloudArchetype)EditorGUILayout.EnumPopup("Archetype", layer.Archetype);
            layer.Seed = EditorGUILayout.IntField("Seed", layer.Seed);
            layer.Density = EditorGUILayout.Slider("Density", layer.Density, 0f, 1f);
            layer.Jitter = EditorGUILayout.Slider("Jitter", layer.Jitter, 0f, 1f);
            layer.Clustering = EditorGUILayout.Slider("Clustering", layer.Clustering, 0f, 1f);
            layer.PositionVariation = EditorGUILayout.Slider("Position Variation", layer.PositionVariation, 0f, 2f);
            layer.YOffset = EditorGUILayout.FloatField("Y Offset", layer.YOffset);

            if (layer.Archetype == CloudArchetype.Sphere)
            {
                EditorGUILayout.LabelField("Sphere Settings", EditorStyles.boldLabel);
                layer.CloudSize = EditorGUILayout.Slider("Cloud Size", layer.CloudSize, 20f, 200f);
                layer.CascadeDepth = EditorGUILayout.IntSlider("Cascade Depth", layer.CascadeDepth, 1, 5);
                layer.BumpsPerLevel = EditorGUILayout.IntSlider("Bumps/Level", layer.BumpsPerLevel, 2, 128);
                layer.ChildRatio = EditorGUILayout.Slider("Child Ratio", layer.ChildRatio, 10f, 200f);
                layer.SizeVariation = EditorGUILayout.Slider("Size Variation", layer.SizeVariation, 0f, 1.5f);
                layer.ParentCount = EditorGUILayout.IntSlider("Parent Count", layer.ParentCount, 1, 12);
                layer.EllipsoidY = EditorGUILayout.Slider("Ellipsoid Y", layer.EllipsoidY, 20f, 150f);
                layer.EllipsoidXZ = EditorGUILayout.Slider("Ellipsoid XZ", layer.EllipsoidXZ, 50f, 150f);
                layer.MaxSphereCount = EditorGUILayout.IntSlider("Max Sphere Count", layer.MaxSphereCount, 5, 10000);
                layer.SphereCountScale = EditorGUILayout.Slider("Sphere Count Scale %", layer.SphereCountScale * 100f, 1f, 400f) * 0.01f;

                EditorGUILayout.LabelField("Parent Mesh", EditorStyles.boldLabel);
                var meshObj = EditorGUILayout.ObjectField("Mesh Asset", null, typeof(UnityEngine.Mesh), false);
                if (meshObj != null)
                {
                    string assetPath = UnityEditor.AssetDatabase.GetAssetPath(meshObj);
                    if (!string.IsNullOrEmpty(assetPath)) layer.ParentMeshPath = assetPath;
                }
                layer.ParentMeshPath = EditorGUILayout.TextField("Mesh Path", layer.ParentMeshPath);
                if (!string.IsNullOrEmpty(layer.ParentMeshPath))
                {
                    EditorGUILayout.BeginHorizontal();
                    layer.ParentMeshScaleX = EditorGUILayout.Slider("Scale X", layer.ParentMeshScaleX, 0.1f, 3f);
                    layer.ParentMeshScaleY = EditorGUILayout.Slider("Scale Y", layer.ParentMeshScaleY, 0.1f, 3f);
                    layer.ParentMeshScaleZ = EditorGUILayout.Slider("Scale Z", layer.ParentMeshScaleZ, 0.1f, 3f);
                    EditorGUILayout.EndHorizontal();
                    EditorGUILayout.BeginHorizontal();
                    layer.ParentMeshRotX = EditorGUILayout.Slider("Rot X", layer.ParentMeshRotX, -180f, 180f);
                    layer.ParentMeshRotY = EditorGUILayout.Slider("Rot Y", layer.ParentMeshRotY, -180f, 180f);
                    layer.ParentMeshRotZ = EditorGUILayout.Slider("Rot Z", layer.ParentMeshRotZ, -180f, 180f);
                    EditorGUILayout.EndHorizontal();
                    EditorGUILayout.BeginHorizontal();
                    layer.ParentMeshOffsetX = EditorGUILayout.Slider("Offset X", layer.ParentMeshOffsetX, -50f, 50f);
                    layer.ParentMeshOffsetY = EditorGUILayout.Slider("Offset Y", layer.ParentMeshOffsetY, -50f, 50f);
                    layer.ParentMeshOffsetZ = EditorGUILayout.Slider("Offset Z", layer.ParentMeshOffsetZ, -50f, 50f);
                    EditorGUILayout.EndHorizontal();
                }
            }

            if (layer.Archetype == CloudArchetype.Column)
            {
                EditorGUILayout.LabelField("Column Settings", EditorStyles.boldLabel);
                layer.ColumnParams.Height = EditorGUILayout.Slider("Height", layer.ColumnParams.Height, 10f, 100f);
                layer.ColumnParams.BaseRadius = EditorGUILayout.Slider("Base Radius", layer.ColumnParams.BaseRadius, 3f, 30f);
                layer.ColumnParams.TopRadius = EditorGUILayout.Slider("Top Radius", layer.ColumnParams.TopRadius, 0f, 15f);
                layer.ColumnParams.Floors = EditorGUILayout.IntSlider("Floors", layer.ColumnParams.Floors, 3, 20);
                layer.ColumnParams.RingsPerFloor = EditorGUILayout.IntSlider("Rings/Floor", layer.ColumnParams.RingsPerFloor, 3, 12);
            }

            if (layer.Archetype == CloudArchetype.Platform)
            {
                EditorGUILayout.LabelField("Platform Settings", EditorStyles.boldLabel);
                layer.PlatformParams.Width = EditorGUILayout.Slider("Width", layer.PlatformParams.Width, 20f, 200f);
                layer.PlatformParams.Depth = EditorGUILayout.Slider("Depth", layer.PlatformParams.Depth, 20f, 200f);
                layer.PlatformParams.CenterThickness = EditorGUILayout.Slider("Center Thickness", layer.PlatformParams.CenterThickness, 1f, 10f);
                layer.PlatformParams.InteriorDensity = EditorGUILayout.IntSlider("Interior Density", layer.PlatformParams.InteriorDensity, 10, 100);
            }

            if (layer.Archetype == CloudArchetype.Tree)
            {
                EditorGUILayout.LabelField("Tree Settings", EditorStyles.boldLabel);
                layer.TreeParams.MaxDepth = EditorGUILayout.IntSlider("Max Depth", layer.TreeParams.MaxDepth, 2, 8);
                layer.TreeParams.BranchElongation = EditorGUILayout.Slider("Branch Elongation", layer.TreeParams.BranchElongation, 0.5f, 3f);
                layer.TreeParams.BranchAngle = EditorGUILayout.Slider("Branch Angle", layer.TreeParams.BranchAngle, 15f, 60f);
                layer.TreeParams.BranchProbability = EditorGUILayout.Slider("Branch Probability", layer.TreeParams.BranchProbability, 0.2f, 0.8f);
            }

            EditorGUILayout.BeginHorizontal();
            if (GUILayout.Button("Duplicate"))
            {
                layers.Insert(index + 1, new CloudLayerConfig
                {
                    Enabled = layer.Enabled,
                    Archetype = layer.Archetype,
                    Seed = Random.Range(1, 99999),
                    Density = layer.Density,
                    Jitter = layer.Jitter,
                    Clustering = layer.Clustering,
                    PositionVariation = layer.PositionVariation,
                    YOffset = layer.YOffset,
                    CloudSize = layer.CloudSize,
                    CascadeDepth = layer.CascadeDepth,
                    BumpsPerLevel = layer.BumpsPerLevel,
                    ChildRatio = layer.ChildRatio,
                    SizeVariation = layer.SizeVariation,
                    ParentCount = layer.ParentCount,
                    EllipsoidY = layer.EllipsoidY,
                    EllipsoidXZ = layer.EllipsoidXZ,
                    MaxSphereCount = layer.MaxSphereCount,
                    SphereCountScale = layer.SphereCountScale,
                    ParentMeshPath = layer.ParentMeshPath,
                    ParentMeshScaleX = layer.ParentMeshScaleX,
                    ParentMeshScaleY = layer.ParentMeshScaleY,
                    ParentMeshScaleZ = layer.ParentMeshScaleZ,
                    ParentMeshRotX = layer.ParentMeshRotX,
                    ParentMeshRotY = layer.ParentMeshRotY,
                    ParentMeshRotZ = layer.ParentMeshRotZ,
                    ParentMeshOffsetX = layer.ParentMeshOffsetX,
                    ParentMeshOffsetY = layer.ParentMeshOffsetY,
                    ParentMeshOffsetZ = layer.ParentMeshOffsetZ,
                    SizeRange = new SizeRange { Min = layer.SizeRange.Min, Max = layer.SizeRange.Max },
                    ColumnParams = new ColumnParams
                    {
                        Height = layer.ColumnParams.Height,
                        BaseRadius = layer.ColumnParams.BaseRadius,
                        TopRadius = layer.ColumnParams.TopRadius,
                        Floors = layer.ColumnParams.Floors,
                        RingsPerFloor = layer.ColumnParams.RingsPerFloor,
                        Wobble = layer.ColumnParams.Wobble
                    },
                    PlatformParams = new PlatformParams
                    {
                        Width = layer.PlatformParams.Width,
                        Depth = layer.PlatformParams.Depth,
                        CenterThickness = layer.PlatformParams.CenterThickness,
                        EdgeThickness = layer.PlatformParams.EdgeThickness,
                        InteriorDensity = layer.PlatformParams.InteriorDensity,
                        EdgeRings = layer.PlatformParams.EdgeRings
                    },
                    TreeParams = new TreeParams
                    {
                        BaseRadius = layer.TreeParams.BaseRadius,
                        MaxDepth = layer.TreeParams.MaxDepth,
                        BranchElongation = layer.TreeParams.BranchElongation,
                        TaperRatio = layer.TreeParams.TaperRatio,
                        BranchAngle = layer.TreeParams.BranchAngle,
                        BranchProbability = layer.TreeParams.BranchProbability,
                        TrunkUpBias = layer.TreeParams.TrunkUpBias,
                        LengthFalloff = layer.TreeParams.LengthFalloff,
                        ThicknessFalloff = layer.TreeParams.ThicknessFalloff
                    }
                });
            }
            if (GUILayout.Button("Delete"))
            {
                layers.RemoveAt(index);
            }
            EditorGUILayout.EndHorizontal();

            EditorGUI.indentLevel--;
        }
    }
}
