// CloudGenerator.cs v6.0
// Generated by Cloud Generator Visualizer
// DO NOT EDIT - Regenerate from visualizer

using System;
using System.Collections.Generic;

namespace {{NAMESPACE}}.CloudGenerator
{
    /// <summary>
    /// xorshift32 deterministic PRNG — matches deterministic output for a given seed.
    /// </summary>
    public struct DeterministicRandom
    {
        private uint _state;

        public DeterministicRandom(int seed)
        {
            _state = (uint)(seed != 0 ? seed : 1);
            // Warm-up scramble to avoid initial correlation
            for (int i = 0; i < 10; i++)
            {
                uint x = _state;
                x ^= x << 13;
                x ^= x >> 17;
                x ^= x << 5;
                _state = x;
            }
        }

        public uint Next()
        {
            uint x = _state;
            x ^= x << 13;
            x ^= x >> 17;
            x ^= x << 5;
            _state = x;
            return x;
        }

        /// <summary>Returns a double in [0, 1)</summary>
        public double NextDouble()
        {
            return Next() / (double)uint.MaxValue;
        }
    }

    /// <summary>
    /// Multi-archetype cloud generator.
    /// Each layer produces spheres via its archetype generator,
    /// then layers are stacked vertically with gap management.
    /// </summary>
    public static class CloudGenerator
    {
        // ======================================================================
        // PUBLIC API
        // ======================================================================

        public static List<CloudSphere> Generate(List<CloudLayerConfig> layers)
        {
            var allSpheres = new List<CloudSphere>();
            double cumulativeY = 0;

            for (int i = 0; i < layers.Count; i++)
            {
                CloudLayerConfig layer = layers[i];
                if (!layer.Enabled) continue;

                var rng = new DeterministicRandom(layer.Seed);
                List<CloudSphere> rawSpheres;

                switch (layer.Archetype)
                {
                    case CloudArchetype.Sphere:
                        rawSpheres = GenerateSphereLayer(layer, ref rng);
                        break;
                    case CloudArchetype.Column:
                        rawSpheres = GenerateColumnLayer(layer, ref rng);
                        break;
                    case CloudArchetype.Platform:
                        rawSpheres = GeneratePlatformLayer(layer, ref rng);
                        break;
                    case CloudArchetype.Tree:
                        rawSpheres = GenerateTreeLayer(layer, ref rng);
                        break;
                    default:
                        rawSpheres = GenerateSphereLayer(layer, ref rng);
                        break;
                }

                // Compute layer vertical bounds for stacking
                double minY = double.MaxValue;
                double maxY = double.MinValue;
                for (int si = 0; si < rawSpheres.Count; si++)
                {
                    double bottom = rawSpheres[si].Y - rawSpheres[si].Radius;
                    double top = rawSpheres[si].Y + rawSpheres[si].Radius;
                    if (bottom < minY) minY = bottom;
                    if (top > maxY) maxY = top;
                }

                double layerHeight = maxY - minY;
                const double gap = 2.0;

                // If YOffset == 0 (default), auto-stack; otherwise use explicit offset
                double yOffset = Math.Abs(layer.YOffset) > 0.001
                    ? layer.YOffset
                    : cumulativeY - minY + gap;

                bool hasCondensation = layer.CondensationLevel != -999;

                for (int si = 0; si < rawSpheres.Count; si++)
                {
                    CloudSphere s = rawSpheres[si];
                    s.Y += (float)yOffset;
                    s.LayerIndex = i;
                    s.CutByCondensation = hasCondensation && (s.Y - s.Radius < layer.CondensationLevel);
                }

                cumulativeY = yOffset + maxY + gap;
                allSpheres.AddRange(rawSpheres);
            }

            allSpheres.RemoveAll(s => s.CutByCondensation);
            return allSpheres;
        }

        // ======================================================================
        // SPHERE ARCHETYPE — recursive cascade converted to stack-based traversal
        // ======================================================================

        /// <summary>
        /// Internal frame used for stack-based sphere cascade traversal.
        /// Maintains DFS pre-order by pushing modified parent before child.
        /// </summary>
        private struct SphereGenFrame
        {
            public double X, Y, Z;
            public double Radius;
            public int Depth;
            public double Density;

            /// <summary>-1 = uninitialized, otherwise index of next point to process</summary>
            public int NextPointIdx;
            public int BumpCount;
            public (double x, double y, double z)[] SurfacePoints;
        }

        private static List<CloudSphere> GenerateSphereLayer(CloudLayerConfig layer, ref DeterministicRandom rng)
        {
            var spheres = new List<CloudSphere>();
            int globalUniqueId = 0;

            int maxSphereCount = layer.MaxSphereCount;

            double cloudSize = layer.CloudSize;
            double density = layer.Density;
            int seed = layer.Seed;
            int cascadeDepth = layer.CascadeDepth;
            int bumpsPerLevel = layer.BumpsPerLevel;
            double childRatio = layer.ChildRatio;
            double sizeVariation = layer.SizeVariation;
            double jitter = layer.Jitter;
            double clustering = layer.Clustering;
            int parentCount = layer.ParentCount;
            double ellipsoidY = layer.EllipsoidY;
            double ellipsoidXZ = layer.EllipsoidXZ;
            int noiseSalt = layer.NoiseSalt;

            double minRadius = layer.SizeRange.Min;
            double sizeMax = layer.SizeRange.Max;
            double baseRadius = cloudSize * 0.5;

            double rx = baseRadius * (ellipsoidXZ / 100.0);
            double ry = baseRadius * (ellipsoidY / 100.0);
            double rz = baseRadius * (ellipsoidXZ / 100.0);

            double posVariation = layer.PositionVariation;

            // Build parent spheres
            var stack = new Stack<SphereGenFrame>();
            for (int p = 0; p < parentCount; p++)
            {
                double offsetAngle = (p / (double)parentCount) * Math.PI * 2;
                double spread = parentCount > 1 ? (p % 3) * 0.15 : 0;
                double px = Math.Cos(offsetAngle) * rx * spread;
                double py = (p % 2 == 0 ? 1 : -1) * ry * 0.1 * spread;
                double pz = Math.Sin(offsetAngle) * rz * spread;

                spheres.Add(new CloudSphere
                {
                    X = (float)px,
                    Y = (float)py,
                    Z = (float)pz,
                    Radius = (float)baseRadius,
                    Depth = 0,
                    Density = 1.0f,
                    Archetype = CloudArchetype.Sphere
                });

                stack.Push(new SphereGenFrame
                {
                    X = px, Y = py, Z = pz,
                    Radius = baseRadius,
                    Depth = 0,
                    Density = 1.0,
                    NextPointIdx = -1,
                    BumpCount = 0,
                    SurfacePoints = null
                });
            }

            // Iterative stack-based DFS traversal
            while (stack.Count > 0 && spheres.Count < maxSphereCount)
            {
                SphereGenFrame frame = stack.Pop();

                // ---- INITIALIZATION (first time processing this frame) ----
                if (frame.NextPointIdx == -1)
                {
                    if (frame.Depth >= cascadeDepth) continue;
                    if (frame.Radius < minRadius * 1.5) continue;

                    // Bump count from noise
                    double noiseForBumpCount = (CloudMath.Perlin3D(
                        frame.X * 0.5, frame.Y * 0.5, frame.Z * 0.5,
                        seed + frame.Depth * 7) + 1.0) * 0.5;
                    int actualBumps = (int)Math.Floor(bumpsPerLevel * (0.4 + noiseForBumpCount * 0.8));

                    var surfacePoints = CloudMath.FibonacciSphere(
                        frame.X, frame.Y, frame.Z,
                        frame.Radius, frame.Radius, frame.Radius,
                        actualBumps);

                    frame.NextPointIdx = 0;
                    frame.BumpCount = actualBumps;
                    frame.SurfacePoints = surfacePoints;
                }

                // ---- PROCESS POINTS ----
                if (frame.NextPointIdx >= frame.BumpCount) continue; // done

                int idx = frame.NextPointIdx;
                (double x, double y, double z) pt = frame.SurfacePoints[idx];

                // Surface normal
                double nx = (pt.x - frame.X) / frame.Radius;
                double ny = (pt.y - frame.Y) / frame.Radius;
                double nz = (pt.z - frame.Z) / frame.Radius;

                // Jitter
                double jitterStrength = jitter / 100.0;
                double jitX = CloudMath.Perlin3D(pt.x * 15, pt.y * 15, pt.z * 15, seed) * jitterStrength;
                double jitY = CloudMath.Perlin3D(pt.x * 15, pt.y * 15, pt.z * 15, seed + 1) * jitterStrength;
                double jitZ = CloudMath.Perlin3D(pt.x * 15, pt.y * 15, pt.z * 15, seed + 2) * jitterStrength;
                double jptX = pt.x + jitX * frame.Radius;
                double jptY = pt.y + jitY * frame.Radius;
                double jptZ = pt.z + jitZ * frame.Radius;

                double noiseScale = 3.0 / frame.Radius;

                double worleyVal = CloudMath.InvertedWorley(
                    jptX * noiseScale * 2, jptY * noiseScale * 2, jptZ * noiseScale * 2,
                    1.0, noiseSalt);

                double clusterStrength = clustering / 100.0;

                double fbmVal = (CloudMath.Fbm(
                    jptX * noiseScale, jptY * noiseScale, jptZ * noiseScale,
                    4, 0.5, 2.0, seed + frame.Depth * 10) + 1.0) * 0.5;

                double bumpIntensity = fbmVal * (1.0 - clusterStrength * 0.5)
                                       + worleyVal * clusterStrength * 0.5;

                double threshold = 1.0 - density;

                // Threshold check with Worley override
                if (bumpIntensity < threshold)
                {
                    if (!(worleyVal > 0.75 && rng.NextDouble() < 0.15))
                    {
                        // Move to next point
                        frame.NextPointIdx = idx + 1;
                        if (frame.NextPointIdx < frame.BumpCount)
                            stack.Push(frame);
                        continue;
                    }
                }

                // Child radius
                double phiNoise = (CloudMath.Perlin3D(
                    jptX * noiseScale, jptY * noiseScale, jptZ * noiseScale,
                    seed + 100) + 1.0) * 0.5;
                double effectiveRatio = (CloudMath.PHI + (phiNoise - 0.5) * 0.6)
                                        * (childRatio / 100.0) * 0.4;

                int childUniqueId = globalUniqueId++;

                double sizeNoiseBase = Math.Pow(
                    (CloudMath.Perlin3D(
                        jptX * noiseScale * 2, jptY * noiseScale * 2, jptZ * noiseScale * 2,
                        seed + childUniqueId) + 1.0) * 0.5, 1.5);
                double sizeNoiseMult = Math.Pow(
                    (CloudMath.Perlin3D(
                        jptX * noiseScale * 2 + 100, jptY * noiseScale * 2 + 100, jptZ * noiseScale * 2 + 100,
                        seed + childUniqueId + 500) + 1.0) * 0.5, 1.5);

                double sizeBase = minRadius + sizeNoiseBase * (sizeMax - minRadius);
                double sizeMult = (0.05 + sizeNoiseMult * sizeVariation * 2.0 + effectiveRatio) * 0.3;
                double childRadius = sizeBase * sizeMult;

                if (childRadius < minRadius * 0.1)
                {
                    frame.NextPointIdx = idx + 1;
                    if (frame.NextPointIdx < frame.BumpCount)
                        stack.Push(frame);
                    continue;
                }

                // Perturb position
                var perturbed = CloudMath.PerturbDir(
                    nx, ny, nz, jptX, jptY, jptZ, 0.25, seed + frame.Depth);

                double posOffX = (rng.NextDouble() - 0.5) * 12.0 * frame.Radius * posVariation;
                double posOffY = (rng.NextDouble() - 0.5) * 12.0 * frame.Radius * posVariation;
                double posOffZ = (rng.NextDouble() - 0.5) * 12.0 * frame.Radius * posVariation;

                double childX = jptX + perturbed.x * frame.Radius * 0.02 + posOffX;
                double childY = jptY + perturbed.y * frame.Radius * 0.02 + posOffY;
                double childZ = jptZ + perturbed.z * frame.Radius * 0.02 + posOffZ;

                var childSphere = new CloudSphere
                {
                    X = (float)childX,
                    Y = (float)childY,
                    Z = (float)childZ,
                    Radius = (float)childRadius,
                    Depth = frame.Depth + 1,
                    Density = (float)bumpIntensity,
                    Archetype = CloudArchetype.Sphere
                };
                spheres.Add(childSphere);
                if (spheres.Count >= maxSphereCount) break;

                // Push parent frame back with updated index
                frame.NextPointIdx = idx + 1;
                if (frame.NextPointIdx < frame.BumpCount)
                    stack.Push(frame);

                // Determine if we should recurse into child
                double continueChance = Math.Max(0.15, 0.8 - frame.Depth * 0.2);
                bool shouldRecurse = (rng.NextDouble() < continueChance || frame.Depth < 2)
                                     && spheres.Count < maxSphereCount;

                if (shouldRecurse)
                {
                    stack.Push(new SphereGenFrame
                    {
                        X = childX, Y = childY, Z = childZ,
                        Radius = childRadius,
                        Depth = frame.Depth + 1,
                        Density = bumpIntensity,
                        NextPointIdx = -1,
                        BumpCount = 0,
                        SurfacePoints = null
                    });
                }
            }

            return spheres;
        }

        // ======================================================================
        // COLUMN ARCHETYPE — vertical stacking
        // ======================================================================

        private static List<CloudSphere> GenerateColumnLayer(CloudLayerConfig layer, ref DeterministicRandom rng)
        {
            var spheres = new List<CloudSphere>();

            int seed = layer.Seed;
            double jitter = layer.Jitter;
            double clustering = layer.Clustering;
            double posVariation = layer.PositionVariation;
            int sizeMin = layer.SizeRange.Min;
            int sizeMax = layer.SizeRange.Max;

            double height = layer.ColumnParams.Height;
            double baseRadius = layer.ColumnParams.BaseRadius;
            double topRadius = layer.ColumnParams.TopRadius;
            int floors = layer.ColumnParams.Floors;
            int ringsPerFloor = layer.ColumnParams.RingsPerFloor;
            double wobble = layer.ColumnParams.Wobble / 100.0;

            double floorSpacing = height / floors;

            for (int floor = 0; floor < floors; floor++)
            {
                double t = floor / (double)(floors - 1 <= 0 ? 1 : floors - 1);
                double floorRadius = baseRadius + (topRadius - baseRadius) * t;

                double y = floor * floorSpacing;

                double wobbleX = CloudMath.Perlin3D(floor * 0.7, 0, 0, seed)
                                 * wobble * floorRadius
                                 + jitter * baseRadius * 2.0
                                   * CloudMath.Perlin3D(floor, 0, 0, seed + 1);
                double wobbleZ = CloudMath.Perlin3D(floor * 0.7, 0, 0, seed + 100)
                                 * wobble * floorRadius
                                 + jitter * baseRadius * 2.0
                                   * CloudMath.Perlin3D(floor, 0, 0, seed + 2);

                for (int r = 0; r < ringsPerFloor; r++)
                {
                    double angle = (r / (double)ringsPerFloor) * Math.PI * 2
                                   + CloudMath.Perlin3D(floor * 0.3, r * 0.5, seed, seed)
                                     * 0.5 * (1.0 + jitter * 2.0);
                    double distNoise = CloudMath.Perlin3D(floor * 0.5, r * 0.7, seed + 50, seed);
                    double distFromCenter = floorRadius
                                            * (0.3 + (distNoise + 1.0) * 0.5 * 0.7 + 0.5)
                                            * 0.5;
                    double jitR = CloudMath.Perlin3D(floor, r, seed, seed) * jitter * 0.5;

                    double rNoiseBase = Math.Pow(
                        (CloudMath.Perlin3D(floor + r * 0.1, r + floor * 0.1, seed + 200, seed)
                         + 1.0) * 0.5, 1.8);
                    double rNoiseMult = Math.Pow(
                        (CloudMath.Perlin3D(floor + r * 0.1 + 50, r + floor * 0.1 + 50, seed + 250, seed)
                         + 1.0) * 0.5, 1.5);
                    double sizeBase = sizeMin + rNoiseBase * (sizeMax - sizeMin);
                    double sphereRadius = baseRadius * sizeBase * 0.12 * (0.1 + rNoiseMult * 0.9);

                    double colOx = (rng.NextDouble() - 0.5) * 12.0 * sphereRadius * posVariation;
                    double colOy = (rng.NextDouble() - 0.5) * 12.0 * sphereRadius * posVariation;
                    double colOz = (rng.NextDouble() - 0.5) * 12.0 * sphereRadius * posVariation;

                    spheres.Add(new CloudSphere
                    {
                        X = (float)(Math.Cos(angle) * distFromCenter + wobbleX + colOx),
                        Y = (float)(y + jitR * 0.3 + colOy),
                        Z = (float)(Math.Sin(angle) * distFromCenter + wobbleZ + colOz),
                        Radius = (float)Math.Max(sphereRadius, 0.5),
                        Depth = 0,
                        Density = (float)(0.6 + (1.0 - t) * 0.3),
                        Archetype = CloudArchetype.Column
                    });
                }

                // Center sphere on even floors
                if (floor % 2 == 0)
                {
                    spheres.Add(new CloudSphere
                    {
                        X = (float)wobbleX,
                        Y = (float)y,
                        Z = (float)wobbleZ,
                        Radius = (float)(floorRadius * 0.3),
                        Depth = 0,
                        Density = 0.8f,
                        Archetype = CloudArchetype.Column
                    });
                }
            }

            return spheres;
        }

        // ======================================================================
        // PLATFORM ARCHETYPE — flat horizontal spread
        // ======================================================================

        private static List<CloudSphere> GeneratePlatformLayer(CloudLayerConfig layer, ref DeterministicRandom rng)
        {
            var spheres = new List<CloudSphere>();

            int seed = layer.Seed;
            double jitter = layer.Jitter;
            double clustering = layer.Clustering;
            double posVariation = layer.PositionVariation;
            int sizeMin = layer.SizeRange.Min;

            double width = layer.PlatformParams.Width;
            double depth = layer.PlatformParams.Depth;
            double centerThickness = layer.PlatformParams.CenterThickness;
            double edgeThickness = layer.PlatformParams.EdgeThickness;
            int interiorDensity = layer.PlatformParams.InteriorDensity;

            double baseRadius = sizeMin;

            spheres.Add(new CloudSphere
            {
                X = 0, Y = 0, Z = 0,
                Radius = (float)baseRadius,
                Depth = 0, Density = 1.0f,
                Archetype = CloudArchetype.Platform
            });

            (double x, double z)[] interiorPoints = CloudMath.FibonacciSpiral2D(interiorDensity);
            int spiralIdx = 0;

            for (int pi = 0; pi < interiorPoints.Length; pi++)
            {
                (double x, double z) pt = interiorPoints[pi];
                double px = pt.x * width * 0.5;
                double pz = pt.z * depth * 0.5;

                double dist = Math.Sqrt(
                    (px * px) / (width * width * 0.25) + (pz * pz) / (depth * depth * 0.25));
                double thickness = centerThickness * Math.Exp(-dist * dist * 3.0)
                                   + edgeThickness * dist;
                if (thickness < 0.2) continue;

                double yNoise = CloudMath.Perlin3D(px * 0.3, pz * 0.3, seed + 500, seed);
                double y = yNoise * thickness * 0.5
                           + jitter * baseRadius * CloudMath.Perlin3D(px, pz, seed, seed + 1);

                double rNoiseBase = Math.Pow(
                    (CloudMath.Perlin3D(px * 0.5, pz * 0.5, seed + 600 + spiralIdx, seed)
                     + 1.0) * 0.5, 1.8);
                double rNoiseMult = Math.Pow(
                    (CloudMath.Perlin3D(px * 0.5 + 70, pz * 0.5 + 70, seed + 650 + spiralIdx, seed + 1)
                     + 1.0) * 0.5, 1.5);
                double sizeBase = sizeMin + rNoiseBase * (layer.SizeRange.Max - sizeMin);
                double jitterFactor = 1.0 + jitter * (1.0 - clustering);
                double radius = sizeBase * (0.1 + rNoiseMult * 0.9) * jitterFactor;

                double densityVal = (0.3 + 0.7 * (1.0 - dist))
                                    * (clustering > 0.5 ? (0.7 + rNoiseBase * 0.3) : 1.0);

                if (densityVal < 0.1 || radius < 0.3) { spiralIdx++; continue; }

                double platOx = (rng.NextDouble() - 0.5) * 12.0 * radius * posVariation;
                double platOy = (rng.NextDouble() - 0.5) * 12.0 * radius * posVariation;
                double platOz = (rng.NextDouble() - 0.5) * 12.0 * radius * posVariation;

                spheres.Add(new CloudSphere
                {
                    X = (float)(px + platOx),
                    Y = (float)(y + platOy),
                    Z = (float)(pz + platOz),
                    Radius = (float)radius,
                    Depth = 0,
                    Density = (float)densityVal,
                    Archetype = CloudArchetype.Platform
                });
                spiralIdx++;
            }

            return spheres;
        }

        // ======================================================================
        // TREE ARCHETYPE — directional branching (already stack-based in JS)
        // ======================================================================

        private struct TreeFrame
        {
            public double X, Y, Z;
            public double DirX, DirY, DirZ;
            public double Radius;
            public int Depth;
            public int PathId;
            public double LengthMult;
        }

        private static List<CloudSphere> GenerateTreeLayer(CloudLayerConfig layer, ref DeterministicRandom rng)
        {
            var spheres = new List<CloudSphere>();
            int globalPathId = 0;

            int seed = layer.Seed;
            double jitter = layer.Jitter;
            double clustering = layer.Clustering;
            double posVariation = layer.PositionVariation;
            int sizeMin = layer.SizeRange.Min;
            int sizeMax = layer.SizeRange.Max;

            double baseRadius = layer.TreeParams.BaseRadius;
            int maxDepth = layer.TreeParams.MaxDepth;
            double branchElongation = layer.TreeParams.BranchElongation;
            double taperRatio = layer.TreeParams.TaperRatio;
            double branchAngle = layer.TreeParams.BranchAngle * Math.PI / 180.0;
            double trunkUpBias = layer.TreeParams.TrunkUpBias;
            double lengthFalloff = layer.TreeParams.LengthFalloff;
            double thicknessFalloff = layer.TreeParams.ThicknessFalloff;

            // Root sphere
            spheres.Add(new CloudSphere
            {
                X = 0, Y = 0, Z = 0,
                Radius = sizeMin,
                Depth = 0, Density = 1.0f,
                Archetype = CloudArchetype.Tree
            });

            var stack = new Stack<TreeFrame>();
            stack.Push(new TreeFrame
            {
                X = 0, Y = 0, Z = 0,
                DirX = 0, DirY = 1, DirZ = 0,
                Radius = sizeMin,
                Depth = 0, PathId = 0, LengthMult = 1.0
            });

            while (stack.Count > 0)
            {
                TreeFrame frame = stack.Pop();
                if (frame.Depth >= maxDepth) continue;
                if (frame.Radius < 0.5) continue;

                double dirLen = Math.Sqrt(
                    frame.DirX * frame.DirX + frame.DirY * frame.DirY + frame.DirZ * frame.DirZ);
                if (dirLen < 1e-15) continue;
                double dirNX = frame.DirX / dirLen;
                double dirNY = frame.DirY / dirLen;
                double dirNZ = frame.DirZ / dirLen;

                double extension = frame.Radius * branchElongation * frame.LengthMult;

                // Perturb direction deterministically
                double a1 = CloudMath.Perlin3D(frame.X * 3, frame.Y * 3, frame.Z * 3, seed + frame.PathId)
                            * branchAngle;
                double a2 = CloudMath.Perlin3D(frame.X * 3, frame.Y * 3, frame.Z * 3 + 50, seed + frame.PathId + 1)
                            * branchAngle;
                double cos1 = Math.Cos(a1), sin1 = Math.Sin(a1);
                double cos2 = Math.Cos(a2), sin2 = Math.Sin(a2);

                double pdx = dirNX * cos1 - dirNY * sin1;
                double pdy = dirNX * sin1 + dirNY * cos1;
                double pdz = dirNZ;
                double pdx2 = pdx * cos2 + pdz * sin2;
                double pdy2 = pdy;
                double pdz2 = -pdx * sin2 + pdz * cos2;
                double pLen = Math.Sqrt(pdx2 * pdx2 + pdy2 * pdy2 + pdz2 * pdz2);
                if (pLen < 1e-15) continue;
                double perturbedDirX = pdx2 / pLen;
                double perturbedDirY = pdy2 / pLen;
                double perturbedDirZ = pdz2 / pLen;

                // Jitter the perturbed direction
                double jitterAngle = jitter * Math.PI
                                     * CloudMath.Perlin3D(frame.X, frame.Y, frame.PathId, seed);
                double jCos = Math.Cos(jitterAngle), jSin = Math.Sin(jitterAngle);
                double jDirX = jCos * perturbedDirX - jSin * perturbedDirY;
                double jDirY = jCos * perturbedDirY + jSin * perturbedDirX;
                double jDirZ = perturbedDirZ;

                // Child position
                double childPosX = frame.X + jDirX * extension
                                   + jitter * baseRadius * CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 50, seed);
                double childPosY = frame.Y + jDirY * extension
                                   + jitter * baseRadius * CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 60, seed);
                double childPosZ = frame.Z + jDirZ * extension
                                   + jitter * baseRadius * CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 70, seed);

                // Child radius
                double sizeNoiseBase = Math.Pow(
                    (CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 80, seed) + 1.0) * 0.5, 1.8);
                double sizeNoiseMult = Math.Pow(
                    (CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 82, seed) + 1.0) * 0.5, 1.5);
                double radiusNoise = Math.Pow(
                    (CloudMath.Perlin3D(frame.Depth, frame.PathId, seed + 81, seed) + 1.0) * 0.5, 2.0);
                double szBase = sizeMin + sizeNoiseBase * (sizeMax - sizeMin);
                double childRadius = szBase * taperRatio * thicknessFalloff
                                     * (0.1 + sizeNoiseMult * 0.9)
                                     * (0.3 + radiusNoise * 0.7);
                double childDensity = 1.0 - (frame.Depth / (double)maxDepth) * 0.3;

                // Position jitter
                double treeOx = (rng.NextDouble() - 0.5) * 12.0 * childRadius * posVariation;
                double treeOy = (rng.NextDouble() - 0.5) * 12.0 * childRadius * posVariation;
                double treeOz = (rng.NextDouble() - 0.5) * 12.0 * childRadius * posVariation;

                spheres.Add(new CloudSphere
                {
                    X = (float)(childPosX + treeOx),
                    Y = (float)(childPosY + treeOy),
                    Z = (float)(childPosZ + treeOz),
                    Radius = (float)childRadius,
                    Depth = frame.Depth + 1,
                    Density = (float)childDensity,
                    Archetype = CloudArchetype.Tree
                });

                // Continue main branch
                stack.Push(new TreeFrame
                {
                    X = childPosX, Y = childPosY, Z = childPosZ,
                    DirX = perturbedDirX, DirY = perturbedDirY, DirZ = perturbedDirZ,
                    Radius = childRadius,
                    Depth = frame.Depth + 1,
                    PathId = frame.PathId,
                    LengthMult = frame.LengthMult * lengthFalloff
                });

                // Lateral branches
                double val = (CloudMath.Perlin3D(
                                 frame.X * 2, frame.Y * 2, frame.Z * 2, seed + frame.PathId)
                             + 1.0) * 0.5;
                int lateralCount;
                if (val < 0.4) lateralCount = 0;
                else if (val < 0.75) lateralCount = 1;
                else if (val < 0.95) lateralCount = 2;
                else lateralCount = 3;

                for (int i = 0; i < lateralCount; i++)
                {
                    int lateralPathId = ++globalPathId;
                    double lateralAngle = (i / (double)Math.Max(lateralCount, 1)) * Math.PI * 2
                                          + CloudMath.Perlin3D(frame.PathId * 10, i * 5, seed, seed)
                                            * 0.5 * (1.0 + jitter);

                    double perpX = -dirNZ;
                    double perpZ = dirNX;
                    double latDirX = dirNX * Math.Cos(branchAngle)
                                     + perpX * Math.Sin(lateralAngle) * Math.Sin(branchAngle);
                    double latDirY = dirNY * Math.Cos(branchAngle)
                                     + Math.Sin(branchAngle) * 0.5;
                    double latDirZ = dirNZ * Math.Cos(branchAngle)
                                     + perpZ * Math.Sin(lateralAngle) * Math.Sin(branchAngle);

                    double latLen = Math.Sqrt(latDirX * latDirX + latDirY * latDirY + latDirZ * latDirZ);
                    if (latLen < 1e-15) continue;
                    latDirX /= latLen;
                    latDirY /= latLen;
                    latDirZ /= latLen;

                    double lateralRadius = childRadius * 0.7;
                    if (lateralRadius < 0.5) continue;

                    double lateralPosX = frame.X + latDirX * extension * 0.8;
                    double lateralPosY = frame.Y + latDirY * extension * 0.8;
                    double lateralPosZ = frame.Z + latDirZ * extension * 0.8;

                    double latOx = (rng.NextDouble() - 0.5) * 12.0 * lateralRadius * posVariation;
                    double latOy = (rng.NextDouble() - 0.5) * 12.0 * lateralRadius * posVariation;
                    double latOz = (rng.NextDouble() - 0.5) * 12.0 * lateralRadius * posVariation;

                    spheres.Add(new CloudSphere
                    {
                        X = (float)(lateralPosX + latOx),
                        Y = (float)(lateralPosY + latOy),
                        Z = (float)(lateralPosZ + latOz),
                        Radius = (float)lateralRadius,
                        Depth = frame.Depth + 1,
                        Density = (float)(childDensity * 0.8),
                        Archetype = CloudArchetype.Tree
                    });

                    if (frame.Depth + 1 < maxDepth - 1)
                    {
                        stack.Push(new TreeFrame
                        {
                            X = lateralPosX, Y = lateralPosY, Z = lateralPosZ,
                            DirX = latDirX, DirY = latDirY, DirZ = latDirZ,
                            Radius = lateralRadius,
                            Depth = frame.Depth + 2,
                            PathId = lateralPathId,
                            LengthMult = frame.LengthMult * lengthFalloff * 0.8
                        });
                    }
                }
            }

            return spheres;
        }
    }
}
